;; -*- lexical-binding: t; -*-
(require 'ert)
(require 'agent-rig)

(defmacro agent-rig-test-with-server (&rest body)
  `(let ((agent-rig-tmux-socket (format "agent-rig-test-%s-%s" (emacs-pid) (random 1000000))))
     (unwind-protect (condition-case failure (progn ,@body)
                       (error
                        (message "tmux inventory: %S"
                                 (agent-rig-tmux--call "list-panes" "-a" "-F"
                                                      "#{session_name}|#{pane_id}|#{pane_dead}|#{@agent-rig}|#{bracket_paste_flag}|#{pane_start_command}"))
                        (dolist (session (agent-rig-tmux-sessions))
                          (message "tmux history: %S"
                                   (agent-rig-tmux--call "capture-pane" "-p" "-S" "-"
                                                        "-t" (alist-get 'pane session))))
                        (signal (car failure) (cdr failure))))
       (ignore-errors (agent-rig-tmux--run "kill-server")))))

(defun agent-rig-test-wait (predicate)
  (let ((deadline (+ (float-time) 5)))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (accept-process-output nil 0.05))
    (should (funcall predicate))))

(ert-deftest agent-rig-provider-validates-before-launch ()
  (let ((agent-rig-providers '((missing :command ("agent-rig-no-such-executable")))))
    (should-error (agent-rig-provider-command 'missing) :type 'user-error)
    (should-error (agent-rig-provider-command 'unknown) :type 'user-error)))

(ert-deftest agent-rig-rejects-invalid-identities-and-remote-paths ()
  (dolist (name '("" "-bad" "a:b" "a.b" "a\nb" "a;b"))
    (should-error (agent-rig--name name) :type 'user-error))
  (should (equal (agent-rig--name "reviewer_2-main") "reviewer_2-main"))
  (should-error (agent-rig--metadata "team" "seat" 'codex "/ssh:example:/tmp/")
                :type 'user-error))

(ert-deftest agent-rig-team-preflight-does-not-launch-partial-team ()
  (let ((agent-rig-teams '(("pair" ("one" valid) ("two" missing))))
        (agent-rig-providers '((valid :command ("sh"))
                               (missing :command ("agent-rig-no-such-executable"))))
        launched)
    (cl-letf (((symbol-function 'agent-rig-tmux-start)
               (lambda (&rest _) (setq launched t))))
      (should-error (agent-rig-start-team "pair" temporary-file-directory) :type 'user-error)
      (should-not launched))))

(ert-deftest agent-rig-team-rejects-duplicate-seats ()
  (let ((agent-rig-teams '(("pair" ("one" valid) ("one" valid))))
        (agent-rig-providers '((valid :command ("sh")))))
    (should-error (agent-rig-start-team "pair" temporary-file-directory) :type 'user-error)))

(ert-deftest agent-rig-discovery-rejects-corrupt-metadata ()
  (cl-letf (((symbol-function 'agent-rig-tmux--call)
             (lambda (&rest _) '(0 . "ar-test|%1|0||invalid!"))))
    (should-not (agent-rig-tmux-sessions))))

(ert-deftest agent-rig-discovery-does-not-hide-server-errors ()
  (cl-letf (((symbol-function 'agent-rig-tmux--call)
             (lambda (&rest _) '(1 . "permission denied"))))
    (should-error (agent-rig-tmux-sessions))))

(ert-deftest agent-rig-paste-refuses-control-characters-and-unready-terminals ()
  (let ((session '((status . "running") (pane . "%1"))) calls)
    (cl-letf (((symbol-function 'agent-rig-tmux--run)
               (lambda (&rest args) (push args calls) "0")))
      (should-error (agent-rig-tmux-paste session "bad\033text") :type 'user-error)
      (should-not calls)
      (should-error (agent-rig-tmux-paste session "hello") :type 'user-error)
      (should (equal (mapcar #'car calls) '("display-message"))))))

(ert-deftest agent-rig-prompt-retry-does-not-duplicate-successful-deliveries ()
  (let ((sessions '(((session . "one")) ((session . "two")))) delivered)
    (with-temp-buffer
      (insert "hello")
      (setq-local agent-rig--prompt-targets '("one" "two"))
      (cl-letf (((symbol-function 'agent-rig-tmux-sessions) (lambda () sessions))
                ((symbol-function 'agent-rig-tmux-paste)
                 (lambda (item _text)
                   (if (equal (alist-get 'session item) "two")
                       (error "not ready")
                     (push (alist-get 'session item) delivered)))))
        (should-error (agent-rig-paste-prompt))
        (should (equal delivered '("one")))
        (should (equal agent-rig--prompt-targets '("two")))))))

(ert-deftest agent-rig-paste-supports-both-tmux-sanitization-contracts ()
  (dolist (usage '("paste-buffer (pasteb) [-dpr]" "paste-buffer (pasteb) [-dprS]"))
    (let (paste)
      (cl-letf (((symbol-function 'agent-rig-tmux--run)
                 (lambda (&rest args)
                   (cond
                    ((equal (car args) "display-message") "1")
                    ((equal (car args) "list-commands") usage)
                    ((equal (car args) "paste-buffer") (setq paste args))
                    (t "")))))
        (agent-rig-tmux-paste '((status . "running") (pane . "%1")) "line one\nline two")
        (should (equal (not (null (member "-S" paste)))
                       (not (null (string-match-p "dprS" usage)))))))))

(ert-deftest agent-rig-metadata-roundtrip ()
  (let* ((metadata (agent-rig--metadata "team" "seat" 'codex temporary-file-directory))
         (encoded (agent-rig-tmux--encode metadata)))
    (should (equal metadata (agent-rig-tmux--decode encoded)))
    (cl-letf (((symbol-function 'agent-rig-tmux--call)
               (lambda (&rest _) (cons 0 (concat "ar-test|%1|0||" encoded)))))
      (should (= 1 (length (agent-rig-tmux-sessions)))))))

(ert-deftest agent-rig-team-rolls-back-only-new-sessions ()
  (let ((agent-rig-teams '(("pair" ("one" valid) ("two" valid))))
        (agent-rig-providers '((valid :command ("sh"))))
        (attempt 0) stopped)
    (cl-letf (((symbol-function 'agent-rig-tmux-sessions) (lambda () nil))
              ((symbol-function 'agent-rig-tmux-start)
               (lambda (&rest _)
                 (setq attempt (1+ attempt))
                 (if (= attempt 1) "new-session" (error "launch failed"))))
              ((symbol-function 'agent-rig-tmux--run)
               (lambda (&rest args) (push args stopped))))
      (should-error (agent-rig-start-team "pair" temporary-file-directory))
      (should (equal stopped '(("kill-session" "-t" "=new-session")))))))

(ert-deftest agent-rig-server-persists-and-isolates-projects ()
  (agent-rig-test-with-server
   (let* ((directory (make-temp-file "agent-rig-project-" t))
          (agent-rig-providers '((fixture :command ("sh" "-c" "exec sleep 60"))))
          first second)
     (unwind-protect
         (progn
           (should-not (agent-rig-tmux-sessions))
           (setq first (agent-rig-start "team" "seat" 'fixture temporary-file-directory))
           (setq second (agent-rig-start "team" "seat" 'fixture directory))
           (should-not (equal first second))
           (should (= 2 (length (agent-rig-tmux-sessions))))
           (should-error (agent-rig-start "team" "seat" 'fixture directory))
           (should (= 2 (length (agent-rig-tmux-sessions))))
           (with-temp-buffer
             (should (zerop (call-process invocation-name nil t nil "-Q" "--batch"
                                         "-L" default-directory "-l" "agent-rig"
                                         "--eval" (prin1-to-string
                                                   `(progn
                                                      (setq agent-rig-tmux-socket ,agent-rig-tmux-socket)
                                                      (princ (length (agent-rig-tmux-sessions))))))))
             (should (equal (buffer-string) "2"))))
       (delete-directory directory)))))

(ert-deftest agent-rig-exited-agent-retains-status-and-output ()
  (agent-rig-test-with-server
   (let* ((agent-rig-providers '((fixture :command ("sh" "-c" "printf failure; exit 7"))))
          (id (agent-rig-start "team" "seat" 'fixture temporary-file-directory)))
     (agent-rig-test-wait
      (lambda () (equal (alist-get 'status (car (agent-rig-tmux-sessions))) "exited")))
     (let ((session (car (agent-rig-tmux-sessions))))
       (should (equal (alist-get 'session session) id))
       (should (equal (alist-get 'exit-code session) "7"))
       (should (string-match-p "failure" (agent-rig-tmux--run "capture-pane" "-p" "-S" "-" "-t"
                                                                          (alist-get 'pane session))))))))

(ert-deftest agent-rig-preserves-arguments-and-multiline-paste ()
  (agent-rig-test-with-server
   (let* ((directory (make-temp-file "agent rig ' project-" t))
          (output (expand-file-name "output" directory))
          (literal "$(touch SHOULD_NOT_EXIST); ' quoted λ")
          (agent-rig-providers
           `((fixture :command
              ("sh" "-c" "stty -echo -icanon; printf '\033[?2004h'; printf '%s\\n' \"$2\" > \"$1\"; exec cat >> \"$1\""
               "fixture" ,output ,literal))))
          (text "first\nsecond $(touch ALSO_NOT_CREATED)\nλ")
          session)
     (unwind-protect
         (progn
           (agent-rig-start "team" "seat" 'fixture directory)
           (setq session (car (agent-rig-tmux-sessions)))
           (if (string-empty-p (agent-rig-tmux--run "display-message" "-p" "-t"
                                                  (alist-get 'pane session) "#{bracket_paste_flag}"))
               (should-error (agent-rig-tmux-paste session text) :type 'user-error)
             (progn
           (agent-rig-test-wait
            (lambda () (equal "1" (agent-rig-tmux--run "display-message" "-p" "-t"
                                                     (alist-get 'pane session) "#{bracket_paste_flag}"))))
           (agent-rig-tmux-paste session text)
           (agent-rig-test-wait
            (lambda ()
              (and (file-exists-p output)
                   (with-temp-buffer
                     (insert-file-contents output)
                     (equal (buffer-string) (concat literal "\n\033[200~" text "\033[201~"))))))
           (should-not (file-exists-p (expand-file-name "SHOULD_NOT_EXIST" directory)))
           (should-not (file-exists-p (expand-file-name "ALSO_NOT_CREATED" directory))))))
       (when (file-exists-p output)
         (message "fixture received: %S" (with-temp-buffer (insert-file-contents output) (buffer-string))))
       (delete-directory directory t)))))

(ert-deftest agent-rig-dashboard-keeps-project-context-and-filters ()
  (let ((agent-rig-refresh-interval nil)
        (directory (file-name-as-directory (file-truename temporary-file-directory))))
    (with-temp-buffer
      (agent-rig-mode)
      (setq-local agent-rig--project-directory directory)
      (let ((sessions `(((session . "one") (team . "team") (seat . "one")
                         (provider . "codex") (status . "running") (directory . ,directory))
                        ((session . "two") (team . "team") (seat . "two")
                         (provider . "claude-code") (status . "running") (directory . "/other/")))))
        (cl-letf (((symbol-function 'agent-rig-tmux-sessions) (lambda () sessions)))
          (agent-rig-refresh)
          (should (equal (mapcar #'car tabulated-list-entries) '("one")))
          (should (equal (agent-rig--directory) directory))
          (agent-rig-toggle-projects)
          (should (= (length tabulated-list-entries) 2)))))))

(ert-deftest agent-rig-empty-dashboard-explains-next-action ()
  (let ((agent-rig-refresh-interval nil))
    (with-temp-buffer
      (agent-rig-mode)
      (cl-letf (((symbol-function 'agent-rig-tmux-sessions) (lambda () nil)))
        (agent-rig-refresh)
        (should (text-property-any (point-min) (point-max) 'agent-rig-command #'agent-rig-start))
        (agent-rig-refresh)
        (goto-char (point-min))
        (should (= 1 (how-many "No agents" (point-min) (point-max))))))))

(ert-deftest agent-rig-context-identifies-file-lines-and-unsaved-state ()
  (with-temp-buffer
    (insert "first\nsecond\nthird\n")
    (setq buffer-file-name "/tmp/project/example.el")
    (setq-local agent-rig--project-directory "/tmp/project/")
    (should (equal (agent-rig--context 7 14)
                   "File: example.el\nLines: 2-2\nBuffer has unsaved changes: yes\n\nsecond\n"))))

(ert-deftest agent-rig-terminal-map-preserves-user-navigation ()
  (let ((agent-rig--source-window (selected-window))
        (session '((session . "ar-test") (directory . "/tmp/")
                   (team . "team") (seat . "seat") (provider . "codex"))))
    (with-temp-buffer
      (let ((map (make-sparse-keymap)))
        (define-key map (kbd "M-w") #'other-window)
        (use-local-map map))
      (cl-letf (((symbol-function 'agent-rig--display) #'ignore))
        (agent-rig--prepare-terminal (current-buffer) session))
      (should (eq (key-binding (kbd "M-w")) #'other-window))
      (should (eq (key-binding (kbd "C-c a")) #'agent-rig))
      (should (eq (key-binding (kbd "C-c C-o")) #'agent-rig-return-to-code))
      (should (equal agent-rig--terminal-session "ar-test")))))

(ert-deftest agent-rig-dashboard-cancels-its-timer-on-kill ()
  (let ((buffer (generate-new-buffer " *agent-rig-timer*"))
        (agent-rig-refresh-interval 3) timer)
    (unwind-protect
        (progn
          (with-current-buffer buffer
            (agent-rig-mode)
            (setq timer agent-rig--refresh-timer))
          (should (timerp timer))
          (kill-buffer buffer)
          (should-not (memq timer timer-idle-list)))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(ert-deftest agent-rig-prompt-composition-preserves-source-and-project ()
  (let ((source (selected-window)) (agent-rig--source-window nil) composed
        (session '((session . "ar-test") (directory . "/tmp/")
                   (team . "team") (seat . "seat") (provider . "codex"))))
    (unwind-protect
        (cl-letf (((symbol-function 'agent-rig--display) (lambda (buffer) (setq composed buffer))))
          (agent-rig--compose (list session) "hello")
          (should (eq agent-rig--source-window source))
          (with-current-buffer composed
            (should (derived-mode-p 'agent-rig-prompt-mode))
            (should (equal default-directory "/tmp/"))
            (should (equal agent-rig--prompt-targets '("ar-test")))
            (should (equal (buffer-string) "hello"))
            (should (eq (key-binding (kbd "C-c C-c")) #'agent-rig-paste-prompt))))
      (when (buffer-live-p composed) (kill-buffer composed)))))

(ert-deftest agent-rig-panel-keeps-source-visible-and-returnable ()
  (let ((source (generate-new-buffer " *agent-rig-source*"))
        (panel (generate-new-buffer " *agent-rig-panel*"))
        (agent-rig-display-buffer-action nil)
        (agent-rig--source-window nil))
    (unwind-protect
        (save-window-excursion
          (delete-other-windows)
          (switch-to-buffer source)
          (agent-rig--remember-source)
          (agent-rig--display panel)
          (should (eq (window-buffer) panel))
          (should (get-buffer-window source))
          (agent-rig-return-to-code)
          (should (eq (window-buffer) source)))
      (kill-buffer source)
      (kill-buffer panel))))

(ert-deftest agent-rig-refresh-retains-selected-agent-after-list-changes ()
  (let ((agent-rig-refresh-interval nil)
        (sessions '(((session . "one") (team . "z") (seat . "one")
                     (provider . "codex") (status . "running") (directory . "/tmp/")))))
    (with-temp-buffer
      (agent-rig-mode)
      (setq-local agent-rig--project-directory "/tmp/")
      (cl-letf (((symbol-function 'agent-rig-tmux-sessions) (lambda () sessions)))
        (agent-rig-refresh)
        (should (equal (tabulated-list-get-id) "one"))
        (push '((session . "two") (team . "a") (seat . "two") (provider . "codex")
                (status . "running") (directory . "/tmp/")) sessions)
        (agent-rig-refresh)
        (should (equal (tabulated-list-get-id) "one"))
        (should-not display-line-numbers)))))

(ert-deftest agent-rig-resume-requires-explicit-safe-id ()
  (let ((agent-rig-providers '((codex :command ("sh") :resume ("resume")))))
    (should (equal (cdr (agent-rig-provider-resume-command 'codex "session-123"))
                   '("resume" "session-123")))
    (dolist (id '("" "--last" "a\nb" "a b"))
      (should-error (agent-rig-provider-resume-command 'codex id) :type 'user-error))))

(ert-deftest agent-rig-snapshot-validates-every-seat-before-starting ()
  (let* ((agent-rig-state-directory (make-temp-file "agent-rig-state-" t))
         (file (expand-file-name "project.json" agent-rig-state-directory))
         (directory (file-name-as-directory (file-truename temporary-file-directory)))
         (seat (agent-rig--metadata "team" "one" 'codex directory))
         launched)
    (unwind-protect
        (progn
          (agent-rig-state--write file `((version . 1) (project . ,directory)
                                         (seats . ,(vector seat seat))))
          (cl-letf (((symbol-function 'agent-rig-tmux-start)
                     (lambda (&rest _) (setq launched t))))
            (should-error (agent-rig-restore file) :type 'user-error)
            (should-not launched)))
      (delete-directory agent-rig-state-directory t))))

(ert-deftest agent-rig-snapshot-survives-server-loss-and-restore-is-idempotent ()
  (agent-rig-test-with-server
   (let* ((agent-rig-state-directory (make-temp-file "agent-rig-state-" t))
          (agent-rig-providers '((fixture :command ("sh" "-c" "sleep 30"))))
          (agent-rig--project-directory temporary-file-directory)
          file)
     (unwind-protect
         (progn
           (agent-rig-start "team" "one" 'fixture temporary-file-directory)
           (setq file (agent-rig-save))
           (should (= (logand (file-modes file) #o777) #o600))
           (agent-rig-tmux--run "kill-server")
           (agent-rig-test-wait (lambda () (null (agent-rig-tmux-sessions))))
           (cl-letf (((symbol-function 'agent-rig--display) #'ignore))
             (should (equal (alist-get 'result (car (agent-rig-restore file)))
                            "fresh conversation launched"))
             (should (equal (alist-get 'result (car (agent-rig-restore file)))
                            "already present; unchanged")))
           (should (= (length (agent-rig-tmux-sessions)) 1))
           (should (file-exists-p (expand-file-name "last-restore.json" agent-rig-state-directory))))
       (delete-directory agent-rig-state-directory t)))))

(ert-deftest agent-rig-adoption-preserves-process-and-rejects-seat-collision ()
  (agent-rig-test-with-server
   (let* ((pane (agent-rig-tmux--run "new-session" "-d" "-P" "-F" "#{pane_id}"
                                    "-s" "outside" "-c" temporary-file-directory "sleep 30"))
          (pid (agent-rig-tmux--run "display-message" "-p" "-t" pane "#{pane_pid}"))
          (agent-rig-providers '((fixture :command ("sh")))))
     (should (= (length (agent-rig-tmux-unmanaged)) 1))
     (cl-letf (((symbol-function 'completing-read)
                (lambda (prompt choices &rest _)
                  (if (string-prefix-p "Provider" prompt) "fixture" (caar choices))))
               ((symbol-function 'agent-rig-read-provider) (lambda (&rest _) 'fixture))
               ((symbol-function 'read-string)
                (lambda (prompt &rest _) (if (equal prompt "Team: ") "adopted" "worker")))
               ((symbol-function 'agent-rig) #'ignore))
       (agent-rig-adopt))
     (should (equal pid (agent-rig-tmux--run "display-message" "-p" "-t" pane "#{pane_pid}")))
     (should-not (agent-rig-tmux-unmanaged))
     (should (equal (alist-get 'session (car (agent-rig-tmux-sessions))) "outside"))
     (should-error (agent-rig-start "adopted" "worker" 'fixture temporary-file-directory)
                   :type 'user-error))))

(ert-deftest agent-rig-focus-restores-source-layout ()
  (save-window-excursion
    (let ((agent-rig--window-configuration nil)
          (buffer (generate-new-buffer " *agent-focus-test*")))
      (unwind-protect
          (progn
            (delete-other-windows)
            (split-window-right)
            (with-current-buffer buffer (agent-rig-prompt-mode))
            (agent-rig--display buffer)
            (let ((count (length (window-list))))
              (agent-rig-toggle-focus)
              (should (= (length (window-list)) 1))
              (should (eq (window-buffer) buffer))
              (agent-rig-toggle-focus)
              (should (= (length (window-list)) count))))
        (when (buffer-live-p buffer) (kill-buffer buffer))))))

(ert-deftest agent-rig-worktree-isolation-preserves-original-checkout ()
  (let* ((root (make-temp-file "agent-rig-git-" t))
         (project (expand-file-name "project/" root))
         (worktree (expand-file-name "isolated" root))
         (agent-rig-providers '((fixture :command ("sh")))))
    (unwind-protect
        (progn
          (make-directory project)
          (let ((default-directory project))
            (should (zerop (process-file "git" nil nil nil "init" "-b" "main")))
            (should (zerop (process-file "git" nil nil nil "-c" "user.name=Test" "-c"
                                         "user.email=test@example.invalid" "commit" "--allow-empty" "-m" "initial")))
            (cl-letf (((symbol-function 'agent-rig-start)
                       (lambda (_team _seat _provider directory)
                         (should (equal directory worktree)) "fixture")))
              (agent-rig-worktree-start "team" "seat" 'fixture project worktree "codex/seat"))
            (with-temp-buffer
              (process-file "git" nil t nil "branch" "--show-current")
              (should (equal (string-trim (buffer-string)) "main"))))
          (should (file-exists-p (expand-file-name ".git" worktree))))
      (delete-directory root t))))

(ert-deftest agent-rig-missing-terminal-never-retargets-another-agent ()
  (with-temp-buffer
    (setq-local agent-rig--terminal-session "vanished")
    (cl-letf (((symbol-function 'agent-rig-tmux-sessions)
               (lambda () '(((session . "different")))))
              ((symbol-function 'completing-read)
               (lambda (&rest _) (ert-fail "Must not offer another target"))))
      (should-error (agent-rig--select) :type 'user-error))))

(ert-deftest agent-rig-handoff-is-editable-and-does-not-send ()
  (let* ((source '((session . "source") (pane . "%1") (team . "team") (seat . "source")
                  (provider . "codex") (directory . "/tmp/")))
         (target '((session . "target") (team . "team") (seat . "target")
                  (provider . "claude-code") (status . "running") (directory . "/tmp/")))
         composed)
    (cl-letf (((symbol-function 'agent-rig--select) (lambda () source))
              ((symbol-function 'agent-rig-tmux-sessions) (lambda () (list source target)))
              ((symbol-function 'agent-rig-tmux--run)
               (lambda (command &rest _)
                 (should (equal command "capture-pane")) "captured result"))
              ((symbol-function 'completing-read) (lambda (_ choices &rest _) (cadr choices)))
              ((symbol-function 'agent-rig--compose)
               (lambda (targets text) (setq composed (list targets text)))))
      (agent-rig-handoff)
      (should (equal (car composed) (list target)))
      (should (string-match-p "captured result" (cadr composed)))
      (should (string-match-p "Objective:" (cadr composed))))))

(ert-deftest agent-rig-dashboard-navigation-keeps-actions-and-target-visible ()
  (let ((agent-rig-refresh-interval nil)
        (sessions '(((session . "one") (team . "team") (seat . "one")
                     (provider . "codex") (status . "running") (directory . "/tmp/"))
                    ((session . "two") (team . "team") (seat . "two")
                     (provider . "claude-code") (status . "running") (directory . "/tmp/")))))
    (with-temp-buffer
      (agent-rig-mode)
      (setq-local agent-rig--project-directory "/tmp/")
      (cl-letf (((symbol-function 'agent-rig-tmux-sessions) (lambda () sessions)))
        (agent-rig-refresh)
        (should hl-line-mode)
        (should (eq (key-binding (kbd "k")) #'agent-rig-previous-row))
        (should (eq (key-binding (kbd "x")) #'agent-rig-stop))
        (agent-rig-next-row)
        (should (equal (tabulated-list-get-id) "two"))
        (agent-rig-next-row)
        (should (equal (tabulated-list-get-id) "two"))
        (should (string-match-p "team/two" (buffer-string)))
        (should (text-property-any (point-min) (point-max) 'agent-rig-command #'agent-rig-send))
        (goto-char (point-max))
        (should (equal (alist-get 'session (agent-rig--select)) "two"))
        (agent-rig-refresh)
        (should (equal (tabulated-list-get-id) "two"))
        (agent-rig-previous-row)
        (should (equal (tabulated-list-get-id) "one"))
        (should-not (buffer-modified-p))))))

(ert-deftest agent-rig-action-menu-retains-originating-seat ()
  (let ((origin (generate-new-buffer " *rig-menu-origin*"))
        (agent-rig-refresh-interval nil)
        (sessions '(((session . "one") (team . "team") (seat . "one")
                     (provider . "codex") (status . "running") (directory . "/tmp/"))))
        result)
    (unwind-protect
        (save-window-excursion
          (switch-to-buffer origin)
          (agent-rig-mode)
          (setq-local agent-rig--project-directory "/tmp/")
          (cl-letf (((symbol-function 'agent-rig-tmux-sessions) (lambda () sessions))
                    ((symbol-function 'agent-rig-send)
                     (lambda () (interactive) (setq result (agent-rig--select)))))
            (agent-rig-refresh)
            (agent-rig-help)
            (set-buffer (window-buffer (selected-window)))
            (should (derived-mode-p 'agent-rig-actions-mode))
            (should (eq agent-rig--action-origin origin))
            (call-interactively (key-binding (kbd "s")))
            (should (equal (alist-get 'session result) "one"))))
      (kill-buffer origin)
      (when (get-buffer "*Agent Rig Actions*") (kill-buffer "*Agent Rig Actions*")))))

(ert-deftest agent-rig-action-panels-fit-width-and-keep-live-buttons ()
  (dolist (width '(36 78 120))
    (with-temp-buffer
      (agent-rig-actions-mode)
      (let ((inhibit-read-only t))
        (cl-letf (((symbol-function 'agent-rig--width) (lambda () width)))
          (agent-rig--insert-actions '("Open" "Create" "Send" "Recovery" "Manage" "View"))))
      (dolist (line (split-string (buffer-string) "\n"))
        (should (<= (string-width line) width)))
      (should (text-property-any (point-min) (point-max) 'agent-rig-command #'agent-rig-start))
      (should (text-property-any (point-min) (point-max) 'agent-rig-command #'agent-rig-stop))
      (should (text-property-any (point-min) (point-max) 'agent-rig-command #'agent-rig-restore)))))

(ert-deftest agent-rig-filter-keeps-row-identities-and-can-be-cleared ()
  (let ((agent-rig-refresh-interval nil)
        (sessions '(((session . "one") (team . "team") (seat . "builder")
                     (provider . "codex") (status . "running") (directory . "/tmp/"))
                    ((session . "two") (team . "team") (seat . "reviewer")
                     (provider . "claude-code") (status . "exited") (exit-code . "0") (directory . "/tmp/")))))
    (with-temp-buffer
      (agent-rig-mode)
      (setq-local agent-rig--project-directory "/tmp/")
      (cl-letf (((symbol-function 'agent-rig-tmux-sessions) (lambda () sessions)))
        (agent-rig-refresh)
        (setq agent-rig--filter "CLAUDE")
        (agent-rig-refresh)
        (should (equal (mapcar #'car tabulated-list-entries) '("two")))
        (should (equal (tabulated-list-get-id) "two"))
        (should (string-match-p "FILTER" (buffer-string)))
        (agent-rig-clear-filter)
        (should (= (length tabulated-list-entries) 2))
        (should (equal (tabulated-list-get-id) "two"))))))

(ert-deftest agent-rig-activity-follows-descendants-not-siblings ()
  (should (equal (mapcar #'car (agent-rig-activity--descendants
                              "10" "30 20 0.0 00:01 worker\n10 1 0.0 00:10 codex\n40 1 0.0 00:10 daemon\n20 10 1.0 00:02 shell\n"))
                 '("30" "20"))))

(ert-deftest agent-rig-native-status-matches-exact-pid ()
  (let ((text "[{\"pid\":12,\"status\":\"busy\"},{\"pid\":42,\"status\":\"idle\"}]"))
    (should (equal (agent-rig-activity--claude-status "42" text) "idle"))
    (should (string-match-p "unavailable" (agent-rig-activity--claude-status "43" text)))))

(ert-deftest agent-rig-navigation-keys-work-in-each-view ()
  (dolist (map (list agent-rig-mode-map agent-rig-terminal-map agent-rig-activity-mode-map))
    (should (eq (lookup-key map (kbd "M-<left>")) #'agent-rig-overview))
    (should (eq (lookup-key map (kbd "M-<right>")) #'agent-rig-open))))

(ert-deftest agent-rig-activity-rejects-late-probe-results ()
  (dolist (reuse-mode '(nil t))
    (with-temp-buffer
      (let (sentinel output rendered transformed)
        (cl-letf (((symbol-function 'run-at-time) (lambda (&rest _) nil))
                  ((symbol-function 'process-put) (lambda (&rest _) nil))
                  ((symbol-function 'process-get) (lambda (&rest _) nil))
                  ((symbol-function 'process-status) (lambda (_) 'exit))
                  ((symbol-function 'process-exit-status) (lambda (_) 0))
                  ((symbol-function 'make-process)
                   (lambda (&rest args)
                     (setq sentinel (plist-get args :sentinel) output (plist-get args :buffer))
                     'probe))
                  ((symbol-function 'agent-rig-activity--render) (lambda () (setq rendered t))))
          (agent-rig-activity-mode)
          (setq agent-rig-activity--generation (list nil))
          (agent-rig-activity--probe 'native '("fixture") (lambda (_) (setq transformed t)))
          (setq agent-rig-activity--processes nil)
          (if reuse-mode (special-mode) (setq agent-rig-activity--generation (list nil)))
          (funcall sentinel 'probe "finished")
          (should-not transformed)
          (should-not rendered)
          (should-not (buffer-live-p output)))))))

(ert-deftest agent-rig-activity-marks-a-disappeared-agent-stale ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'run-at-time) (lambda (&rest _) nil))
              ((symbol-function 'get-buffer-window) (lambda (&rest _) t))
              ((symbol-function 'agent-rig-activity-refresh) (lambda () (user-error "Agent disappeared"))))
      (agent-rig-activity-mode)
      (agent-rig-activity--tick (current-buffer))
      (should (string-match-p "STALE SNAPSHOT: Agent disappeared" (buffer-string)))
      (should (string-match-p "Activity stopped" header-line-format)))))

(ert-deftest agent-rig-native-record-rejects-stale-or-unrelated-pids ()
  (let* ((session `((provider . "claude-code") (status . "running") (pid . "42")
                    (directory . ,temporary-file-directory)))
         (record `((pid . 42) (startedAt . 2000) (status . "busy")
                   (cwd . ,temporary-file-directory))))
    (cl-letf (((symbol-function 'file-attributes) (lambda (_) '(fixture)))
              ((symbol-function 'file-attribute-size) (lambda (_) 100))
              ((symbol-function 'json-read-file) (lambda (_) record))
              ((symbol-function 'process-attributes)
               (lambda (_) (list (cons 'start (seconds-to-time 1))))))
      (should (equal (alist-get 'status (agent-rig-activity--native-record session)) "busy"))
      (setf (alist-get 'pid record) 43)
      (should-not (agent-rig-activity--native-record session))
      (setf (alist-get 'pid record) 42 (alist-get 'startedAt record) 500)
      (should-not (agent-rig-activity--native-record session))
      (setf (alist-get 'startedAt record) (* 1000 (+ (float-time) 60)))
      (should-not (agent-rig-activity--native-record session))
      (setf (alist-get 'startedAt record) 2000 (alist-get 'cwd record) "/")
      (should-not (agent-rig-activity--native-record session))
      (setf (alist-get 'cwd record) temporary-file-directory (alist-get 'status session) "exited")
      (should-not (agent-rig-activity--native-record session)))))

(ert-deftest agent-rig-codex-descendants-follow-native-parent-identities ()
  (let ((threads '(((id . "unrelated") (parentThreadId . "other"))
                   ((id . "grandchild") (parentThreadId . "child"))
                   ((id . "child") (source . ((subAgent . ((thread_spawn . ((parent_thread_id . "root"))))))))
                   ((id . "root") (parentThreadId . "grandchild")))))
    (should (equal (mapcar (lambda (thread) (alist-get 'id thread))
                          (agent-rig-codex--descendants "root" threads)) '("child" "grandchild")))))

(ert-deftest agent-rig-codex-snapshot-keeps-state-tools-and-children-distinct ()
  (let (observed cancelled requests)
    (cl-letf (((symbol-function 'agent-rig-codex--client)
               (lambda (ready _failed)
                 (funcall ready
                          (lambda (method params callback)
                            (push method requests)
                            (funcall callback nil
                                     (cond
                                      ((equal method "thread/read")
                                       `((thread . ((id . "root") (cwd . ,temporary-file-directory)
                                                    (status . ((type . "active") (activeFlags . ("waitingOnApproval"))))))))
                                      ((equal method "thread/list")
                                       (if (alist-get 'cursor params)
                                           '((data . (((id . "child") (parentThreadId . "root")
                                                       (agentNickname . "Worker") (status . ((type . "active")))))))
                                         '((data . (((id . "old") (parentThreadId . "root") (status . ((type . "notLoaded"))))))
                                           (nextCursor . "page-two"))))
                                      ((equal method "thread/items/list")
                                       '((data . (((item . ((type . "commandExecution") (command . "make check") (status . "inProgress")))))))))))
                          (lambda () (setq cancelled t))))))
      (agent-rig-codex-snapshot "root" temporary-file-directory
                                (lambda (error result) (should-not error) (setq observed result))))
    (should cancelled)
    (should (equal (alist-get 'native observed) "active (waitingOnApproval)"))
    (should (string-match-p "Worker.*active" (alist-get 'subagents observed)))
    (should-not (string-match-p "old" (alist-get 'subagents observed)))
    (should (string-match-p "make check" (alist-get 'tools observed)))
    (should (= (cl-count "thread/list" requests :test #'equal) 2))))

(ert-deftest agent-rig-codex-client-is-read-only-and-ignores-cancelled-results ()
  (let (opened received request cancel sent failures timer-callback responses)
    (cl-letf (((symbol-function 'agent-rig-codex--connect)
               (lambda (open receive _failed) (setq opened open received receive) 'socket))
              ((symbol-function 'websocket-send-text) (lambda (_socket text) (push text sent)))
              ((symbol-function 'websocket-frame-text) #'identity)
              ((symbol-function 'websocket-close) #'ignore)
              ((symbol-function 'run-at-time)
               (lambda (_time _repeat callback) (setq timer-callback callback) nil)))
      (agent-rig-codex--client
       (lambda (send stop) (setq request send cancel stop))
       (lambda (error) (push error failures)))
      (funcall opened 'socket)
      (funcall received 'socket "{\"id\":1,\"result\":{}}")
      (should-error (funcall request "turn/start" nil #'ignore))
      (funcall request "thread/read" '((threadId . "root")) (lambda (&rest result) (push result responses)))
      (should (= (length sent) 2))
      (funcall cancel)
      (funcall received 'socket "{\"id\":2,\"result\":{\"thread\":{\"id\":\"root\"}}}")
      (funcall timer-callback)
      (should-not responses)
      (should-not failures))))

(ert-deftest agent-rig-codex-snapshot-rejects-project-mismatch ()
  (let (failure methods)
    (cl-letf (((symbol-function 'agent-rig-codex--client)
               (lambda (ready _failed)
                 (funcall ready
                          (lambda (method _params callback)
                            (push method methods)
                            (funcall callback nil '((thread . ((id . "root") (cwd . "/"))))))
                          #'ignore))))
      (agent-rig-codex-snapshot "root" temporary-file-directory (lambda (error _result) (setq failure error))))
    (should (string-match-p "does not match" failure))
    (should (equal methods '("thread/read")))))

(ert-deftest agent-rig-opencode-discovers-only-owned-loopback-ports ()
  (should (equal (agent-rig-opencode--ports
                  "p42\nf3\nn127.0.0.1:4096\nn*:8000\nn192.168.1.2:8080\nn127.0.0.1:4096\nn127.0.0.1:99999\n")
                 '(4096))))

(ert-deftest agent-rig-opencode-child-status-keeps-parent-and-directory-boundaries ()
  (let* ((directory temporary-file-directory)
         (children `((("id" . "child") ("parentID" . "root") ("title" . "worker") ("directory" . ,directory))
                     (("id" . "other") ("parentID" . "unrelated") ("title" . "unrelated") ("directory" . ,directory))
                     (("id" . "away") ("parentID" . "root") ("title" . "worktree") ("directory" . "/"))))
         (statuses '(("child" . (("type" . "busy"))) ("away" . (("type" . "busy")))))
         (text (agent-rig-opencode--children "root" directory children statuses)))
    (should (string-match-p "worker.*busy" text))
    (should-not (string-match-p "unrelated" text))
    (should (string-match-p "worktree.*unavailable" text))
    (should (equal (agent-rig-opencode--status "absent" statuses) "idle"))))

(defun agent-rig-test-opencode-http (status-json)
  (let ((process-environment (copy-sequence process-environment)) queue commands inputs result)
    (setenv "OPENCODE_SERVER_PASSWORD" "fixture-secret")
    (cl-letf (((symbol-function 'run-at-time) (lambda (&rest _) nil))
              ((symbol-function 'process-live-p) (lambda (_) nil))
              ((symbol-function 'process-status) (lambda (_) 'exit))
              ((symbol-function 'process-exit-status) (lambda (_) 0))
              ((symbol-function 'process-send-string) (lambda (_ text) (push text inputs)))
              ((symbol-function 'process-send-eof) #'ignore)
              ((symbol-function 'make-process)
               (lambda (&rest args)
                 (let* ((command (plist-get args :command))
                        (url (car (last command)))
                        (reply (cond
                                ((equal (car command) "lsof") "p42\nn127.0.0.1:4096\n")
                                ((string-match-p "/global/health?" url) "{\"healthy\":true,\"version\":\"fixture\"}")
                                ((string-match-p "/session/status?" url) status-json)
                                ((string-match-p "/children?" url) "[]")
                                ((string-match-p "/message?" url) "[{\"parts\":[{\"type\":\"tool\",\"tool\":\"bash\",\"state\":{\"status\":\"running\",\"title\":\"make check\"}}]}]")
                                (t (json-encode `((id . "root") (directory . ,temporary-file-directory)))))))
                   (push command commands)
                   (with-current-buffer (plist-get args :buffer) (insert reply))
                   (setq queue (append queue (list (plist-get args :sentinel))))
                   'fixture))))
      (agent-rig-opencode-snapshot `((status . "running") (pid . "42") (conversation . "root") (directory . ,temporary-file-directory))
                                  (lambda (error value) (setq result (list error value))))
      (while queue (funcall (pop queue) 'fixture "finished")))
    (list result commands inputs)))

(ert-deftest agent-rig-opencode-http-reads-bound-session-with-private-auth ()
  (pcase-let* ((`(,result ,commands ,inputs) (agent-rig-test-opencode-http "{\"root\":{\"type\":\"busy\"}}"))
               (snapshot (cadr result)))
    (should-not (car result))
    (should (equal (alist-get 'native snapshot) "busy"))
    (should (equal (alist-get 'subagents snapshot) "No direct child sessions."))
    (should (string-match-p "bash.*running.*make check" (alist-get 'tools snapshot)))
    (should (= (length commands) 6))
    (should (cl-some (lambda (command) (string-match-p "limit=10" (car (last command)))) commands))
    (should (cl-every (lambda (command) (not (member "fixture-secret" command))) commands))
    (should (cl-every (lambda (input) (string-prefix-p "header = \"Authorization: Basic " input)) inputs))))

(ert-deftest agent-rig-opencode-http-does-not-treat-malformed-status-as-idle ()
  (dolist (invalid '("null" "[]" "false"))
    (let ((result (car (agent-rig-test-opencode-http invalid))))
      (should (car result))
      (should-not (cadr result)))))

(ert-deftest agent-rig-provider-picker-retains-missing-providers-and-capabilities ()
  (let ((agent-rig-providers '((codex :command ("sh") :resume ("resume"))
                               (custom :command ("rig-impossible-command")))))
    (let ((choices (agent-rig-provider-candidates)))
      (should (equal (mapcar #'cdr choices) '(codex custom)))
      (should (string-match-p "installed.*resume: yes" (caar choices)))
      (should (string-match-p "missing executable" (caadr choices)))
      (should (string-match-p "child agents" (caar choices))))))

(ert-deftest agent-rig-compact-drafts-without-executing ()
  (let ((session '((session . "one") (provider . "codex") (status . "running"))) draft)
    (cl-letf (((symbol-function 'agent-rig--select) (lambda () session))
              ((symbol-function 'agent-rig--compose) (lambda (targets text) (setq draft (list targets text))))
              ((symbol-function 'agent-rig-tmux--run) (lambda (&rest _) (ert-fail "Must not execute"))))
      (agent-rig-compact)
      (should (equal draft (list (list session) "/compact")))
      (setf (alist-get 'status session) "exited")
      (should-error (agent-rig-compact) :type 'user-error))))

(ert-deftest agent-rig-claude-observer-keeps-only-lifecycle-and-resumes ()
  (let* ((agent-rig-claude-observer-directory (make-temp-file "rig-observe-" t))
         (directory (expand-file-name "run-test/events/" agent-rig-claude-observer-directory))
         (seat '((observer . "run-test")))
         (native '((sessionId . "root"))))
    (unwind-protect
        (progn
          (make-directory directory t)
          (agent-rig-claude--event directory '((hook_event_name . "SubagentStart") (session_id . "root")
                                              (agent_id . "session") (agent_type . "worker") (prompt . "SECRET")))
          (should (string-prefix-p "Unavailable" (agent-rig-claude-subagents seat native)))
          (agent-rig-claude--event directory '((hook_event_name . "SessionStart") (session_id . "root")))
          (should (string-match-p "session.*start observed" (agent-rig-claude-subagents seat native)))
          (agent-rig-claude--event directory '((hook_event_name . "SubagentStop") (session_id . "root") (agent_id . "session")))
          (should (string-match-p "stop observed" (agent-rig-claude-subagents seat native)))
          (agent-rig-claude--event directory '((hook_event_name . "SubagentStart") (session_id . "root") (agent_id . "session")))
          (should-not (string-match-p "stop observed" (agent-rig-claude-subagents seat native)))
          (should (string-prefix-p "Unavailable" (agent-rig-claude-subagents seat '((sessionId . "other")))))
          (let ((files (directory-files directory t "\\.json$")))
            (should (= (length files) 2))
            (dolist (file files)
              (should (= (logand (file-modes file) #o777) #o600))
              (with-temp-buffer (insert-file-contents file) (should-not (search-forward "SECRET" nil t))))))
      (delete-directory agent-rig-claude-observer-directory t))))

(ert-deftest agent-rig-claude-plugin-preserves-command-and-input-metadata ()
  (let* ((agent-rig-claude-observer-directory (make-temp-file "rig-plugin-" t))
         (metadata '((provider . "claude-code") (observer . "run-old")))
         (command '("claude" "--settings" "existing.json" "--plugin-dir" "existing-plugin")))
    (unwind-protect
        (let ((prepared (agent-rig-claude-prepare metadata command)))
          (should (equal (seq-take (cdr prepared) (length command)) command))
          (should (equal (alist-get 'observer metadata) "run-old"))
          (should-not (equal (alist-get 'observer (car prepared)) "run-old"))
          (should (file-exists-p (expand-file-name "hooks/hooks.json" (car (last (cdr prepared))))))
          (let ((agent-rig-claude-observe-subagents nil))
            (should-not (alist-get 'observer (car (agent-rig-claude-prepare metadata command))))))
      (delete-directory agent-rig-claude-observer-directory t))))

(ert-deftest agent-rig-handoff-creates-recipient-in-source-workspace ()
  (let* ((source '((session . "source") (pane . "%1") (team . "team") (seat . "source")
                  (provider . "codex") (directory . "/tmp/")))
         (target '((session . "new") (status . "running") (directory . "/tmp/")))
         launched composed)
    (cl-letf (((symbol-function 'agent-rig--select) (lambda () source))
              ((symbol-function 'agent-rig-tmux-sessions) (lambda () (if launched (list source target) (list source))))
              ((symbol-function 'completing-read) (lambda (&rest _) "[Create a new agent]"))
              ((symbol-function 'agent-rig-read-provider) (lambda (&rest _) 'claude-code))
              ((symbol-function 'read-string) (lambda (&rest _) "recipient"))
              ((symbol-function 'agent-rig-start)
               (lambda (&rest args) (setq launched args) "new"))
              ((symbol-function 'agent-rig-tmux--run) (lambda (&rest _) "context"))
              ((symbol-function 'agent-rig--compose) (lambda (targets text) (setq composed (list targets text)))))
      (agent-rig-handoff)
      (should (equal launched '("team" "recipient" claude-code "/tmp/")))
      (should (equal (car composed) (list target))))))

(ert-deftest agent-rig-restart-restores-metadata-on-respawn-failure ()
  (let* ((session `((session . "old") (pane . "%1") (status . "exited")
                    (team . "team") (seat . "seat") (provider . "codex")
                    (directory . ,temporary-file-directory) (conversation . "old-id") (observer . "run-old")))
         updates cleaned)
    (cl-letf (((symbol-function 'agent-rig--select) (lambda () session))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'agent-rig-provider-command) (lambda (_) '("codex")))
              ((symbol-function 'agent-rig-claude-prepare)
               (lambda (metadata command) (setf (alist-get 'observer metadata) "run-new") (cons metadata command)))
              ((symbol-function 'agent-rig-tmux--run)
               (lambda (command &rest args)
                 (if (equal command "respawn-pane") (error "failure")
                   (push (car (last args)) updates))))
              ((symbol-function 'agent-rig-claude-cleanup) (lambda (record) (push (alist-get 'observer record) cleaned))))
      (should-error (agent-rig-restart))
      (should (equal (car updates) (agent-rig-tmux--encode (agent-rig-state--seat session t))))
      (should (equal cleaned '("run-new")))
      (should-not (alist-get 'observer (agent-rig-state--seat session))))))

(ert-deftest agent-rig-provider-picker-helm-and-completion-return-symbols ()
  (let ((agent-rig-providers '((fixture :command ("sh")))))
    (cl-letf (((symbol-function 'require) (lambda (&rest _) nil))
              ((symbol-function 'completing-read) (lambda (_ choices &rest _) (caar choices))))
      (should (eq (agent-rig-read-provider) 'fixture)))
    (cl-letf (((symbol-function 'require) (lambda (&rest _) t))
              ((symbol-function 'helm)
               (lambda (&rest args)
                 (let* ((source (car (plist-get args :sources)))
                        (candidate (car (alist-get 'candidates source))))
                   (should (assq 'multiline source))
                   (funcall (alist-get 'action source) (cdr candidate))))))
      (should (eq (agent-rig-read-provider) 'fixture)))))
