;; -*- lexical-binding: t; -*-
(require 'json)
(require 'agent-rig-providers)
(require 'agent-rig-tmux)

(defvar agent-rig-state-directory (expand-file-name "agent-rig/" user-emacs-directory))

(defun agent-rig-state--write (file value)
  (make-directory (file-name-directory file) t)
  (let ((temporary (make-temp-file (concat file ".")))
        (coding-system-for-write 'utf-8-unix))
    (unwind-protect
        (progn
          (set-file-modes temporary #o600)
          (write-region (json-encode value) nil temporary nil 'silent)
          (rename-file temporary file t))
      (when (file-exists-p temporary) (delete-file temporary)))))

(defun agent-rig-state--seat (record &optional live)
  (unless (and (listp record)
               (cl-every (lambda (key) (stringp (alist-get key record)))
                         '(team seat provider directory)))
    (user-error "Malformed saved seat"))
  (let* ((provider (intern-soft (alist-get 'provider record)))
         (conversation (alist-get 'conversation record))
         (metadata (agent-rig--metadata (alist-get 'team record) (alist-get 'seat record)
                                        provider (alist-get 'directory record))))
    (unless (assq provider agent-rig-providers) (user-error "Unknown saved provider"))
    (when conversation
      (unless (and (stringp conversation)
                   (string-match-p "\\`[A-Za-z0-9][A-Za-z0-9_-]*\\'" conversation))
        (user-error "Invalid saved conversation ID"))
      (push (cons 'conversation conversation) metadata))
    (when (and live (alist-get 'observer record))
      (push (cons 'observer (alist-get 'observer record)) metadata))
    metadata))

(defun agent-rig-save ()
  (interactive)
  (let* ((directory (file-name-as-directory (file-truename (agent-rig--directory))))
         (sessions (cl-remove-if-not
                    (lambda (item) (equal directory (alist-get 'directory item)))
                    (agent-rig-tmux-sessions)))
         (file (expand-file-name (concat (secure-hash 'sha256 directory) ".json")
                                 agent-rig-state-directory)))
    (unless sessions (user-error "No agents in this project to save"))
    (agent-rig-state--write file
                            `((version . 1) (project . ,directory)
                              (saved-at . ,(format-time-string "%FT%T%z"))
                              (seats . ,(vconcat (mapcar #'agent-rig-state--seat sessions)))))
    (message "Saved %d seats to %s; seats without conversation IDs restore fresh"
             (length sessions) file)
    file))

(defun agent-rig-set-conversation ()
  (interactive)
  (let* ((session (agent-rig--select))
         (conversation (read-string "Exact provider conversation ID: " nil nil
                                    (alist-get 'conversation session)))
         (metadata (agent-rig-state--seat session t)))
    (agent-rig-provider-resume-command (intern (alist-get 'provider session)) conversation)
    (setf (alist-get 'conversation metadata) conversation)
    (agent-rig-tmux--run "set-option" "-p" "-t" (alist-get 'pane session)
                         "@agent-rig" (agent-rig-tmux--encode metadata))
    (message "Conversation ID recorded; use S to save the project snapshot")))

(defun agent-rig-state--read (file)
  (let* ((json-object-type 'alist) (json-array-type 'list) (json-key-type 'symbol)
         (snapshot (json-read-file file)) seats identities)
    (unless (and (equal (alist-get 'version snapshot) 1)
                 (stringp (alist-get 'project snapshot))
                 (consp (alist-get 'seats snapshot)))
      (user-error "Invalid Agent Rig snapshot"))
    (dolist (record (alist-get 'seats snapshot))
      (let* ((seat (agent-rig-state--seat record))
             (identity (mapcar (lambda (key) (alist-get key seat)) '(team seat directory))))
        (unless (equal (alist-get 'directory seat) (alist-get 'project snapshot))
          (user-error "Snapshot contains a seat from another project"))
        (when (member identity identities) (user-error "Snapshot contains duplicate seats"))
        (push identity identities)
        (push seat seats)))
    (nreverse seats)))

(defun agent-rig-restore (file)
  (interactive (list (read-file-name "Restore snapshot: " agent-rig-state-directory nil t)))
  (let* ((seats (agent-rig-state--read file))
         (existing (agent-rig-tmux-sessions))
         (fresh (cl-count-if-not (lambda (seat) (alist-get 'conversation seat)) seats))
         outcomes)
    (when (and (called-interactively-p 'interactive)
               (not (yes-or-no-p (format "Restore %d seats (%d without saved IDs start fresh)? "
                                         (length seats) fresh))))
      (user-error "Restore cancelled"))
    (dolist (seat seats)
      (let ((result
             (condition-case err
                 (if (cl-find-if
                      (lambda (item)
                        (cl-every (lambda (key) (equal (alist-get key seat) (alist-get key item)))
                                  '(team seat directory))) existing)
                     "already present; unchanged"
                   (let* ((provider (intern (alist-get 'provider seat)))
                          (conversation (alist-get 'conversation seat))
                          (command (if conversation
                                       (agent-rig-provider-resume-command provider conversation)
                                     (agent-rig-provider-command provider))))
                     (agent-rig-tmux-start seat command)
                     (if conversation "resume requested; verify in terminal" "fresh conversation launched")))
               (error (concat "failed: " (error-message-string err))))))
        (push `((team . ,(alist-get 'team seat)) (seat . ,(alist-get 'seat seat))
                (result . ,result)) outcomes)))
    (setq outcomes (nreverse outcomes))
    (agent-rig-state--write (expand-file-name "last-restore.json" agent-rig-state-directory)
                            `((snapshot . ,(expand-file-name file))
                              (time . ,(format-time-string "%FT%T%z"))
                              (outcomes . ,(vconcat outcomes))))
    (with-current-buffer (get-buffer-create "*Agent Rig Recovery*")
      (let ((inhibit-read-only t))
        (erase-buffer)
        (insert "Restore results\n\n")
        (dolist (outcome outcomes)
          (insert (format "%s/%s: %s\n" (alist-get 'team outcome)
                          (alist-get 'seat outcome) (alist-get 'result outcome)))))
      (special-mode)
      (agent-rig--display (current-buffer)))
    outcomes))

(provide 'agent-rig-state)
