;; -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'project)
(require 'tabulated-list)
(require 'button)
(require 'hl-line)
(require 'term)
(require 'agent-rig-providers)
(require 'agent-rig-tmux)
(require 'agent-rig-state)
(require 'agent-rig-worktree)
(require 'agent-rig-activity)

(defface agent-rig-title
  '((((class color) (background dark)) (:foreground "#9bbfff" :weight bold :height 1.15))
    (((class color) (background light)) (:foreground "#315da8" :weight bold :height 1.15))
    (t (:inherit bold))) "")
(defface agent-rig-section '((t (:inherit agent-rig-title :height 1.0))) "")
(defface agent-rig-border
  '((((class color) (background dark)) (:foreground "#60738d"))
    (((class color) (background light)) (:foreground "#77879b"))
    (t (:inherit shadow))) "")
(defface agent-rig-key '((t (:inherit agent-rig-section))) "")
(defface agent-rig-action '((t (:inherit default :underline nil))) "")
(defface agent-rig-selection
  '((((class color) (background dark)) (:background "#22344b" :extend t))
    (((class color) (background light)) (:background "#e1eaf5" :extend t))
    (t (:inherit highlight))) "")

(defvar agent-rig-teams
  '(("pair" ("implementer" codex) ("reviewer" claude-code))
    ("mixed" ("implementer" codex) ("reviewer" claude-code) ("explorer" opencode))))
(defvar agent-rig-terminal-function #'agent-rig-terminal)
(defvar agent-rig-display-buffer-action nil)
(defvar agent-rig-refresh-interval 3)
(defvar agent-rig--source-window nil)
(defvar agent-rig--last-team "default")
(defvar agent-rig--window-configuration nil)
(defvar-local agent-rig--project-directory nil)
(defvar-local agent-rig--show-all nil)
(defvar-local agent-rig--refresh-timer nil)
(defvar vterm-shell)
(defvar vterm-buffer-name-string)
(defvar vterm-kill-buffer-on-exit)
(defvar-local agent-rig--terminal-session nil)
(defvar-local agent-rig--prompt-targets nil)
(defvar-local agent-rig--selected-session nil)
(defvar-local agent-rig--visible-sessions nil)
(defvar-local agent-rig--details-start nil)
(defvar-local agent-rig--details-end nil)
(defvar-local agent-rig--action-origin nil)
(defvar-local agent-rig--filter "")

(defun agent-rig--width ()
  (max 36 (- (window-body-width (get-buffer-window (current-buffer))) 2)))

(defun agent-rig--fit (text width)
  (let ((text (truncate-string-to-width text width nil nil "…")))
    (concat text (make-string (max 0 (- width (string-width text))) ?\s))))

(defun agent-rig--panel (title lines width)
  (let* ((inside (- width 4))
         (title (truncate-string-to-width title (- width 6) nil nil "…"))
         (top (concat (propertize "╭─ " 'face 'agent-rig-border)
                      (propertize title 'face 'agent-rig-section)
                      (propertize (concat " " (make-string (max 0 (- width (string-width title) 5)) ?─) "╮")
                                  'face 'agent-rig-border)))
         (bottom (propertize (concat "╰" (make-string (- width 2) ?─) "╯") 'face 'agent-rig-border)))
    (append (list top)
            (mapcar (lambda (line)
                      (concat (propertize "│ " 'face 'agent-rig-border)
                              (agent-rig--fit line inside)
                              (propertize " │" 'face 'agent-rig-border))) lines)
            (list bottom))))

(defun agent-rig--action-string (entry)
  (let* ((key (concat "[" (car entry) "]"))
         (label (concat (agent-rig--fit key (max 7 (+ 2 (string-width key)))) (nth 2 entry)))
         (text (propertize label 'button t 'category 'default-button
                           'keymap button-map 'agent-rig-command (cadr entry)
                           'action #'agent-rig--button-action 'follow-link t
                           'mouse-face 'highlight 'face 'agent-rig-action
                           'help-echo (symbol-name (cadr entry)))))
    (add-face-text-property 0 (length key) 'agent-rig-key nil text)
    text))

(defun agent-rig--directory ()
  (or agent-rig--project-directory
      (let ((project (project-current nil)))
        (if project
            (if (fboundp 'project-root) (project-root project) (car (project-roots project)))
          default-directory))))

(defun agent-rig--name (name)
  (unless (and (stringp name) (string-match-p "\\`[A-Za-z0-9][A-Za-z0-9_-]*\\'" name))
    (user-error "Names must contain only letters, digits, underscores and hyphens"))
  name)

(defun agent-rig--metadata (team seat provider directory)
  (agent-rig--name team)
  (agent-rig--name seat)
  (when (file-remote-p directory)
    (user-error "Agent Rig supports local project directories"))
  (unless (file-directory-p directory)
    (user-error "Project directory does not exist: %s" directory))
  `((version . 1) (team . ,team) (seat . ,seat)
    (provider . ,(symbol-name provider))
    (directory . ,(file-name-as-directory (file-truename directory)))))

(defun agent-rig--label (session)
  (format "%s/%s [%s] %s" (alist-get 'team session) (alist-get 'seat session)
          (alist-get 'provider session) (alist-get 'directory session)))

(defun agent-rig--select ()
  (let* ((sessions (agent-rig-tmux-sessions))
         (id (or agent-rig--terminal-session
                 (and (derived-mode-p 'agent-rig-mode)
                      (or (tabulated-list-get-id) agent-rig--selected-session))))
         (selected (cl-find id sessions :key (lambda (item) (alist-get 'session item)) :test #'equal)))
    (when (and id (not selected))
      (user-error "This agent disappeared; refresh the dashboard"))
    (or selected
        (let ((choices (mapcar (lambda (item) (cons (agent-rig--label item) item)) sessions)))
          (unless choices (user-error "No managed agents; use agent-rig-start"))
          (cdr (assoc (completing-read "Agent: " choices nil t) choices))))))

(defun agent-rig-start (team seat provider directory)
  (interactive
   (let* ((provider (intern (completing-read "Provider: " agent-rig-providers nil t)))
          (team (read-string "Team: " nil nil agent-rig--last-team))
          (seat (read-string "Seat: " nil nil (symbol-name provider))))
     (list team seat provider (read-directory-name "Project: " (agent-rig--directory) nil t))))
  (let* ((metadata (agent-rig--metadata team seat provider directory))
         (command (agent-rig-provider-command provider))
         (session
          (progn
            (when (cl-find-if
                   (lambda (item)
                     (cl-every (lambda (key) (equal (alist-get key item) (alist-get key metadata)))
                               '(team seat directory)))
                   (agent-rig-tmux-sessions))
              (user-error "This team seat already exists"))
            (agent-rig-tmux-start metadata command))))
    (setq agent-rig--last-team team)
    (when (called-interactively-p 'interactive)
      (agent-rig)
      (agent-rig-open (cl-find session (agent-rig-tmux-sessions)
                               :key (lambda (item) (alist-get 'session item)) :test #'equal)))
    session))

(defun agent-rig-start-team (team directory)
  (interactive
   (list (completing-read "Team template: " agent-rig-teams nil t)
         (read-directory-name "Project: " (agent-rig--directory) nil t)))
  (let ((spec (cdr (assoc team agent-rig-teams))) plans seats existing started)
    (unless spec (user-error "Unknown or empty team: %s" team))
    (dolist (member spec)
      (unless (and (listp member) (= (length member) 2) (symbolp (cadr member)))
        (user-error "Invalid team member: %S" member))
      (when (member (car member) seats) (user-error "Duplicate seat: %s" (car member)))
      (push (car member) seats)
      (push (list (agent-rig--metadata team (car member) (cadr member) directory)
                  (agent-rig-provider-command (cadr member))) plans))
    (setq existing (agent-rig-tmux-sessions))
    (dolist (plan plans)
      (when (cl-find-if
             (lambda (session)
               (cl-every (lambda (key) (equal (alist-get key session) (alist-get key (car plan))))
                         '(team seat directory))) existing)
        (user-error "Seat already exists: %s" (alist-get 'seat (car plan)))))
    (condition-case err
        (dolist (plan (nreverse plans))
          (push (agent-rig-tmux-start (car plan) (cadr plan)) started))
      (error
       (dolist (session started)
         (ignore-errors (agent-rig-tmux--run "kill-session" "-t" (concat "=" session))))
       (signal (car err) (cdr err))))
    (when (called-interactively-p 'interactive) (agent-rig))
    (nreverse started)))

(defun agent-rig--remember-source ()
  (unless (or agent-rig--project-directory agent-rig--terminal-session agent-rig--prompt-targets
              (derived-mode-p 'agent-rig-mode 'agent-rig-prompt-mode))
    (setq agent-rig--source-window (selected-window))))

(defun agent-rig--display (buffer)
  (let* ((side (if (< (frame-width) 160) 'bottom 'right))
         (existing (get-buffer-window buffer))
         (action (or agent-rig-display-buffer-action
                     `((display-buffer-reuse-window display-buffer-in-side-window)
                       (side . ,side) (slot . 0) (window-width . 0.45) (window-height . 0.45)))))
    (when (and (not agent-rig-display-buffer-action) existing
               (window-parameter existing 'window-side)
               (not (eq side (window-parameter existing 'window-side))))
      (delete-window existing))
    (pop-to-buffer buffer action)
    (set-window-hscroll (selected-window) 0)))

(defun agent-rig-return-to-code ()
  (interactive)
  (when agent-rig--window-configuration (agent-rig-toggle-focus))
  (if (window-live-p agent-rig--source-window)
      (select-window agent-rig--source-window)
    (other-window 1)))

(defun agent-rig-toggle-focus ()
  (interactive)
  (if agent-rig--window-configuration
      (let ((configuration agent-rig--window-configuration))
        (setq agent-rig--window-configuration nil)
        (set-window-configuration configuration))
    (let ((buffer (current-buffer)))
      (unless (or agent-rig--terminal-session (derived-mode-p 'agent-rig-mode 'agent-rig-prompt-mode))
        (user-error "Open an Agent Rig buffer first"))
      (setq agent-rig--window-configuration (current-window-configuration))
      (dolist (window (window-list))
        (when (window-parameter window 'window-side) (delete-window window)))
      (delete-other-windows)
      (switch-to-buffer buffer))))

(defun agent-rig--terminal-name (session)
  (format "*Agent Rig %s/%s/%s [%s]*"
          (file-name-nondirectory (directory-file-name (alist-get 'directory session)))
          (alist-get 'team session) (alist-get 'seat session)
          (substring (secure-hash 'sha256 (concat agent-rig-tmux-socket (alist-get 'session session))) 0 6)))

(defun agent-rig-overview ()
  (interactive)
  (let ((identity (or agent-rig--terminal-session agent-rig--selected-session)))
    (with-current-buffer (get-buffer-create "*Agent Rig*")
      (unless (derived-mode-p 'agent-rig-mode) (agent-rig-mode))
      (setq agent-rig--selected-session identity agent-rig--filter "")
      (goto-char (point-min)))
    (agent-rig t)))

(defvar agent-rig-terminal-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "M-<left>") #'agent-rig-overview)
    (define-key map (kbd "M-<right>") #'agent-rig-open)
    (define-key map (kbd "C-c a") #'agent-rig)
    (define-key map (kbd "C-c C-s") #'agent-rig-send)
    (define-key map (kbd "C-c C-o") #'agent-rig-return-to-code)
    (define-key map (kbd "C-c C-n") #'agent-rig-next)
    (define-key map (kbd "C-c C-d") #'agent-rig-detach)
    (define-key map (kbd "C-c C-j") #'agent-rig-submit)
    (define-key map (kbd "C-c C-f") #'agent-rig-toggle-focus)
    map))

(defun agent-rig--prepare-terminal (buffer session)
  (with-current-buffer buffer
    (setq-local display-line-numbers nil)
    (setq-local agent-rig--terminal-session (alist-get 'session session))
    (setq-local agent-rig--project-directory (alist-get 'directory session))
    (setq-local header-line-format
                (format "M-←: all agents | C-c C-o: code | C-c C-f: focus | %s/%s [%s]"
                        (alist-get 'team session) (alist-get 'seat session) (alist-get 'provider session)))
    (use-local-map (make-composed-keymap agent-rig-terminal-map (current-local-map))))
  (agent-rig--display buffer))

(defun agent-rig-terminal (session)
  (if (require 'vterm nil t)
      (agent-rig-vterm session)
    (agent-rig-term session)))

(defun agent-rig-vterm (session)
  (require 'vterm)
  (let* ((name (agent-rig--terminal-name session))
         (buffer (get-buffer name))
         (default-directory (alist-get 'directory session))
         (process-environment (copy-sequence process-environment))
         (vterm-buffer-name-string nil)
         (vterm-kill-buffer-on-exit nil)
         (vterm-shell (mapconcat #'shell-quote-argument
                                (list (or (executable-find agent-rig-tmux-program)
                                          (user-error "tmux is missing"))
                                      "-L" agent-rig-tmux-socket "attach-session" "-t"
                                      (concat "=" (alist-get 'session session))) " ")))
    (setenv "TMUX" nil)
    (unless (and buffer (process-live-p (get-buffer-process buffer)))
      (when buffer (kill-buffer buffer))
      (setq buffer (save-window-excursion (vterm name))))
    (agent-rig--prepare-terminal buffer session)))

(defun agent-rig-term (session)
  (let* ((name (agent-rig--terminal-name session))
         (buffer (get-buffer name))
         (default-directory (alist-get 'directory session))
         (process-environment (copy-sequence process-environment)))
    (setenv "TMUX" nil)
    (unless (and buffer (process-live-p (get-buffer-process buffer)))
      (when buffer (kill-buffer buffer))
      (setq buffer (make-term (substring name 1 -1) agent-rig-tmux-program nil
                              "-L" agent-rig-tmux-socket "attach-session" "-t"
                              (concat "=" (alist-get 'session session))))
      (with-current-buffer buffer (term-mode) (term-char-mode)))
    (agent-rig--prepare-terminal buffer session)))

(defun agent-rig-open (&optional session)
  (interactive)
  (agent-rig--remember-source)
  (funcall agent-rig-terminal-function (or session (agent-rig--select))))

(defun agent-rig-detach ()
  (interactive)
  (unless agent-rig--terminal-session (user-error "This is not an agent terminal"))
  (let ((process (get-buffer-process (current-buffer))))
    (when process (set-process-query-on-exit-flag process nil)))
  (kill-buffer (current-buffer))
  (agent-rig-return-to-code)
  (agent-rig))

(defun agent-rig-switch ()
  (interactive)
  (agent-rig--remember-source)
  (let* ((sessions (agent-rig-tmux-sessions))
         (directory (file-truename (agent-rig--directory)))
         (choices (mapcar (lambda (item) (cons (agent-rig--label item) item))
                          (append (cl-remove-if-not
                                   (lambda (item) (equal directory (alist-get 'directory item))) sessions)
                                  (cl-remove-if
                                   (lambda (item) (equal directory (alist-get 'directory item))) sessions)))))
    (unless choices (user-error "No agents yet; use agent-rig-start"))
    (agent-rig-open (cdr (assoc (completing-read "Switch agent: " choices nil t) choices)))))

(defun agent-rig-next ()
  (interactive)
  (let* ((current (agent-rig--select))
         (sessions (cl-remove-if-not
                    (lambda (item) (equal (alist-get 'directory item) (alist-get 'directory current)))
                    (agent-rig-tmux-sessions)))
         (index (cl-position (alist-get 'session current) sessions
                             :key (lambda (item) (alist-get 'session item)) :test #'equal)))
    (unless index (user-error "Agent disappeared; refresh the dashboard"))
    (agent-rig-open (nth (mod (1+ index) (length sessions)) sessions))))

(defun agent-rig-capture ()
  (interactive)
  (let* ((session (agent-rig--select))
         (text (agent-rig-tmux--run "capture-pane" "-p" "-J" "-S" "-2000"
                                   "-t" (alist-get 'pane session))))
    (with-current-buffer (get-buffer-create "*Agent Rig Output*")
      (let ((inhibit-read-only t))
        (erase-buffer)
        (insert (agent-rig--label session) "\n\n" text))
      (special-mode)
      (setq-local display-line-numbers nil)
      (setq-local agent-rig--project-directory (alist-get 'directory session))
      (setq default-directory agent-rig--project-directory)
      (goto-char (point-min))
      (agent-rig--display (current-buffer)))))

(defun agent-rig-stop ()
  (interactive)
  (let ((session (agent-rig--select)))
    (when (yes-or-no-p (format "Stop %s and discard its terminal history? " (agent-rig--label session)))
      (agent-rig-tmux--run "kill-pane" "-t" (alist-get 'pane session))
      (when (derived-mode-p 'agent-rig-mode) (agent-rig-refresh)))))

(defun agent-rig-adopt ()
  (interactive)
  (let* ((candidates (agent-rig-tmux-unmanaged))
         (choices (mapcar (lambda (item)
                            (cons (format "%s [%s] %s" (alist-get 'session item)
                                          (alist-get 'command item) (alist-get 'directory item)) item))
                          candidates)))
    (unless choices
      (user-error "No unmanaged single-pane sessions on tmux socket %s" agent-rig-tmux-socket))
    (let* ((selected (cdr (assoc (completing-read "Adopt existing terminal: " choices nil t) choices)))
           (provider (intern (completing-read "Provider running in that terminal: " agent-rig-providers nil t)))
           (team (read-string "Team: " nil nil agent-rig--last-team))
           (seat (read-string "Seat: " nil nil (symbol-name provider)))
           (metadata (agent-rig--metadata team seat provider (alist-get 'directory selected))))
      (when (cl-find-if
             (lambda (item) (cl-every (lambda (key) (equal (alist-get key item) (alist-get key metadata)))
                                      '(team seat directory)))
             (agent-rig-tmux-sessions))
        (user-error "This team seat already exists"))
      (agent-rig-tmux--run "set-option" "-p" "-t" (alist-get 'pane selected)
                           "@agent-rig" (agent-rig-tmux--encode metadata))
      (agent-rig-tmux--run "set-option" "-w" "-t" (alist-get 'pane selected) "remain-on-exit" "on")
      (agent-rig)
      (message "Adopted existing process; conversation and terminal state preserved"))))

(defun agent-rig-restart ()
  (interactive)
  (let ((session (agent-rig--select)))
    (unless (equal (alist-get 'status session) "exited")
      (user-error "Only exited agents can be restarted"))
    (when (yes-or-no-p "Start a fresh provider conversation in this seat? ")
      (let ((command (agent-rig-provider-command (intern (alist-get 'provider session))))
            (metadata (assq-delete-all 'conversation (agent-rig-state--seat session))))
        (agent-rig-tmux--run "respawn-pane" "-t" (alist-get 'pane session)
                             "-c" (alist-get 'directory session)
                             (concat "exec " (mapconcat #'shell-quote-argument command " ")))
        (agent-rig-tmux--run "set-option" "-p" "-t" (alist-get 'pane session)
                             "@agent-rig" (agent-rig-tmux--encode metadata)))
      (agent-rig-open session))))

(defvar agent-rig-prompt-mode-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map text-mode-map)
    (define-key map (kbd "C-c C-c") #'agent-rig-paste-prompt)
    (define-key map (kbd "C-c C-o") #'agent-rig-return-to-code)
    map))

(define-derived-mode agent-rig-prompt-mode text-mode "Agent Prompt"
  (setq-local display-line-numbers nil)
  (visual-line-mode 1))

(defun agent-rig--compose (targets &optional text)
  (agent-rig--remember-source)
  (let ((buffer (generate-new-buffer "*Agent Rig Prompt*")))
    (with-current-buffer buffer
      (agent-rig-prompt-mode)
      (setq-local display-line-numbers nil)
      (setq-local agent-rig--project-directory (alist-get 'directory (car targets)))
      (setq default-directory agent-rig--project-directory)
      (setq-local agent-rig--prompt-targets (mapcar (lambda (item) (alist-get 'session item)) targets))
      (setq-local header-line-format
                  (format "C-c C-c: paste draft | C-c C-o: code | To: %s"
                          (mapconcat (lambda (item) (format "%s/%s" (alist-get 'team item)
                                                            (alist-get 'seat item))) targets ", ")))
      (when text (insert text)))
    (agent-rig--display buffer)))

(defun agent-rig-send ()
  (interactive)
  (agent-rig--compose (list (agent-rig--select))))

(defun agent-rig-handoff ()
  (interactive)
  (let* ((source (agent-rig--select))
         (choices (mapcar (lambda (item) (cons (agent-rig--label item) item))
                          (cl-remove-if
                           (lambda (item) (equal (alist-get 'session source) (alist-get 'session item)))
                           (agent-rig-tmux-sessions))))
         (text (agent-rig-tmux--run "capture-pane" "-p" "-J" "-S" "-2000"
                                   "-t" (alist-get 'pane source))))
    (unless choices (user-error "Launch another agent to receive this handoff"))
    (agent-rig--compose
     (list (cdr (assoc (completing-read "Handoff to: " choices nil t) choices)))
     (format "Handoff from %s\n\nTask for recipient:\n\nTerminal output (review and trim before sending):\n\n%s"
             (agent-rig--label source) text))))

(defun agent-rig-submit ()
  (interactive)
  (unless agent-rig--terminal-session
    (user-error "Open the target terminal and inspect its draft before submitting"))
  (let ((session (agent-rig--select)))
    (unless (equal (alist-get 'status session) "running") (user-error "Agent has exited"))
    (when (yes-or-no-p "Send Enter to this agent's visible input? ")
      (agent-rig-tmux--run "send-keys" "-t" (alist-get 'pane session) "Enter")
      (message "Enter sent; inspect the provider for acceptance or approval prompts"))))

(defun agent-rig-send-region (begin end)
  (interactive "r")
  (let ((text (agent-rig--context begin end)))
    (agent-rig--compose (list (agent-rig--select)) text)))

(defun agent-rig--context (begin end)
  (format "File: %s\nLines: %d-%d\nBuffer has unsaved changes: %s\n\n%s"
          (if buffer-file-name (file-relative-name buffer-file-name (agent-rig--directory)) (buffer-name))
          (line-number-at-pos begin) (line-number-at-pos (max begin (1- end)))
          (if (buffer-modified-p) "yes" "no") (buffer-substring-no-properties begin end)))

(defun agent-rig-send-buffer ()
  (interactive)
  (agent-rig-send-region (point-min) (point-max)))

(defun agent-rig-send-diff ()
  (interactive)
  (let* ((directory (agent-rig--directory))
         (text (with-temp-buffer
                 (let ((default-directory directory))
                   (unless (zerop (process-file "git" nil t nil "diff" "--no-ext-diff" "HEAD" "--"))
                     (user-error "Cannot read Git diff: %s" (buffer-string))))
                 (when (zerop (buffer-size)) (user-error "No tracked changes against HEAD"))
                 (concat "Tracked working-tree diff against HEAD (untracked files excluded):\n\n"
                         (buffer-string)))))
    (agent-rig--compose (list (agent-rig--select)) text)))

(defun agent-rig-broadcast ()
  (interactive)
  (let* ((selected (agent-rig--select))
         (targets (cl-remove-if-not
                   (lambda (item)
                     (and (equal (alist-get 'team item) (alist-get 'team selected))
                          (equal (alist-get 'directory item) (alist-get 'directory selected))
                          (equal (alist-get 'status item) "running")))
                   (agent-rig-tmux-sessions))))
    (unless targets (user-error "No running agents in this team"))
    (agent-rig--compose targets)))

(defun agent-rig-paste-prompt ()
  (interactive)
  (unless agent-rig--prompt-targets (user-error "No pending prompt targets"))
  (let ((text (buffer-substring-no-properties (point-min) (point-max)))
        (sessions (agent-rig-tmux-sessions)) delivered)
    (dolist (target (copy-sequence agent-rig--prompt-targets))
      (let ((session (cl-find target sessions :key (lambda (item) (alist-get 'session item)) :test #'equal)))
        (unless session (user-error "Agent disappeared: %s" target))
        (agent-rig-tmux-paste session text)
        (setq agent-rig--prompt-targets (delete target agent-rig--prompt-targets))
        (setq header-line-format (format "Remaining targets: %d | C-c C-c: retry delivery"
                                         (length agent-rig--prompt-targets)))
        (push session delivered)))
    (setq header-line-format "Draft pasted. Submit it in each agent terminal.")
    (set-buffer-modified-p nil)
    (message "Pasted to %d agent(s); submit in their terminals" (length delivered))
    (when (= (length delivered) 1) (agent-rig-open (car delivered)))))

(defun agent-rig-refresh ()
  (interactive)
  (let* ((sessions (agent-rig-tmux-sessions))
         (scoped (if agent-rig--show-all sessions
                   (cl-remove-if-not
                    (lambda (item) (equal (alist-get 'directory item) agent-rig--project-directory)) sessions)))
         (visible (cl-remove-if-not
                   (lambda (item) (string-match-p (regexp-quote (downcase agent-rig--filter))
                                                  (downcase (agent-rig--label item)))) scoped))
         (compact (< (agent-rig--width) 64))
         (show-project (and agent-rig--show-all (>= (agent-rig--width) 100))))
    (setq-local display-line-numbers nil)
    (setq agent-rig--visible-sessions visible)
    (setq agent-rig--selected-session (or (tabulated-list-get-id) agent-rig--selected-session))
    (setq tabulated-list-format
          (vconcat (unless compact '(("Team" 14 t)))
                   (list (list "Seat" (if compact (max 9 (- (agent-rig--width) 29)) 18) t))
                   '(("Provider" 12 t) ("Process" 12 t))
                   (when show-project '(("Project" 0 t)))))
    (setq tabulated-list-sort-key (cons (if compact "Seat" "Team") nil))
    (tabulated-list-init-header)
    (setq tabulated-list-entries
          (mapcar (lambda (session)
                    (list (alist-get 'session session)
                          (vconcat (unless compact (list (alist-get 'team session)))
                                   (list (alist-get 'seat session)
                                  (alist-get 'provider session)
                                  (if (equal (alist-get 'status session) "exited")
                                      (propertize (concat "○ exited:" (alist-get 'exit-code session)) 'face 'warning)
                                    (propertize "● running" 'face 'success)))
                                   (when show-project
                                     (list (abbreviate-file-name (alist-get 'directory session))))))) visible))
    (setq mode-line-process (format " [%d agents | %s]" (length visible)
                                    (if agent-rig--show-all "all projects" "this project")))
    (tabulated-list-print t)
    (let ((inhibit-read-only t)
          (running (cl-count "running" visible :key (lambda (item) (alist-get 'status item)) :test #'equal)))
      (goto-char (point-min))
      (insert (propertize "\n  AGENT RIG" 'face 'agent-rig-title)
              (propertize (concat "  /  " (if agent-rig--show-all "ALL PROJECTS"
                                           (file-name-nondirectory
                                            (directory-file-name (or agent-rig--project-directory default-directory)))))
                          'face 'agent-rig-section)
              "\n")
      (insert (format "  %d seat%s  ·  " (length visible) (if (= (length visible) 1) "" "s"))
              (propertize (format "%d running" running) 'face 'success)
              (propertize (format "  ·  %d exited\n\n" (- (length visible) running)) 'face 'shadow))
      (unless (string-empty-p agent-rig--filter)
        (insert (propertize (format "  FILTER  %s   [Esc] clear\n\n" agent-rig--filter) 'face 'agent-rig-key)))
      (insert (propertize
               (concat "  " (mapconcat (lambda (column)
                                        (agent-rig--fit (upcase (car column)) (max 7 (cadr column))))
                                      (append tabulated-list-format nil) " ") "\n")
               'face 'agent-rig-section)))
    (setq header-line-format
          (propertize "  M-→ open   d activity   s prompt   n new   / filter   : commands   ? actions" 'face 'agent-rig-key))
    (goto-char (point-min))
    (while (and (not (eobp))
                (if agent-rig--selected-session
                    (not (equal (tabulated-list-get-id) agent-rig--selected-session))
                  (not (tabulated-list-get-id))))
      (forward-line 1))
    (when (eobp)
      (goto-char (point-min))
      (while (and visible (not (tabulated-list-get-id)) (not (eobp))) (forward-line 1)))
    (setq agent-rig--selected-session (tabulated-list-get-id))
    (save-excursion
      (goto-char (point-max))
      (let ((inhibit-read-only t))
        (unless visible (insert "\n  No agents here. Press n to launch one, or t for a team.\n"))
        (insert "\n")
        (setq agent-rig--details-start (point-marker))
        (insert "\n")
        (setq agent-rig--details-end (point-marker))
        (insert "\n")
        (dolist (keys '(("RET" "s" "h") ("n" "t" "?")))
          (insert "  ")
          (dolist (key keys)
            (insert (agent-rig--action-string (assoc key agent-rig--commands)) "    "))
          (insert "\n"))
        (insert (propertize "\n  j/k navigate  ·  f focus  ·  q back\n" 'face 'shadow))))
    (agent-rig--selection-changed)
    (set-buffer-modified-p nil)
    (force-mode-line-update)))

(defun agent-rig--selection-changed ()
  (when (tabulated-list-get-id)
    (setq agent-rig--selected-session (tabulated-list-get-id)))
  (when (and (markerp agent-rig--details-start) (marker-position agent-rig--details-start)
             (markerp agent-rig--details-end) (marker-position agent-rig--details-end))
    (let* ((session (cl-find agent-rig--selected-session agent-rig--visible-sessions
                             :key (lambda (item) (alist-get 'session item)) :test #'equal))
           (text (concat
                  (mapconcat
                   #'identity
                   (agent-rig--panel
                    "SELECTED AGENT"
                    (if session
                        (list (propertize (format "%s/%s" (alist-get 'team session) (alist-get 'seat session))
                                          'face 'bold)
                              (format "%s  ·  Process %s%s" (alist-get 'provider session) (alist-get 'status session)
                                      (if (equal (alist-get 'status session) "exited")
                                          (format " (%s)" (alist-get 'exit-code session)) ""))
                              (format "Command %s · PID %s · d activity"
                                      (or (alist-get 'command session) "unknown")
                                      (or (alist-get 'pid session) "unknown"))
                              (propertize (abbreviate-file-name (alist-get 'directory session))
                                          'face 'shadow 'help-echo (alist-get 'directory session)))
                      '("Select an agent above." "n  Create an agent    t  Launch a team"))
                    (agent-rig--width)) "\n") "\n")))
      (unless (equal text (buffer-substring-no-properties agent-rig--details-start agent-rig--details-end))
        (save-excursion
          (let ((inhibit-read-only t))
            (goto-char agent-rig--details-start)
            (delete-region agent-rig--details-start agent-rig--details-end)
            (insert text)
            (set-marker agent-rig--details-end (point))
            (set-buffer-modified-p nil)))))))

(defun agent-rig--move (direction)
  (let ((origin (point)) found)
    (while (and (not found) (zerop (forward-line direction)))
      (when (tabulated-list-get-id) (setq found t)))
    (unless found (goto-char origin))
    (agent-rig--selection-changed)))

(defun agent-rig-next-row ()
  (interactive)
  (agent-rig--move 1))

(defun agent-rig-previous-row ()
  (interactive)
  (agent-rig--move -1))

(defun agent-rig--invoke (command)
  (when agent-rig--action-origin
    (let ((origin agent-rig--action-origin))
      (unless (buffer-live-p origin) (user-error "The original Agent Rig view was closed"))
      (quit-window)
      (agent-rig--display origin)))
  (call-interactively command))

(defun agent-rig--button-action (button)
  (agent-rig--invoke (button-get button 'agent-rig-command)))

(defun agent-rig--insert-actions (groups)
  (let* ((width (agent-rig--width))
         (columns (if (>= width 70) 2 1))
         (panel-width (if (= columns 2) (/ (- width 2) 2) width)))
    (while groups
      (let* ((row (cl-subseq groups 0 (min columns (length groups))))
             (contents (mapcar
                        (lambda (group)
                          (mapcar #'agent-rig--action-string
                                  (cl-remove-if-not (lambda (entry) (equal (nth 3 entry) group))
                                                    agent-rig--commands))) row))
             (height (apply #'max (mapcar #'length contents)))
             (panels (cl-mapcar
                      (lambda (group lines)
                        (agent-rig--panel (upcase group)
                                          (append lines (make-list (- height (length lines)) "")) panel-width))
                      row contents)))
        (dotimes (line (+ height 2))
          (insert (mapconcat (lambda (panel) (nth line panel)) panels "  ") "\n"))
        (insert "\n"))
      (setq groups (nthcdr columns groups)))))

(defun agent-rig-toggle-projects ()
  (interactive)
  (setq agent-rig--show-all (not agent-rig--show-all))
  (agent-rig-refresh))

(defun agent-rig-filter ()
  (interactive)
  (setq agent-rig--filter (read-string "Filter agents: " nil nil agent-rig--filter))
  (agent-rig-refresh))

(defun agent-rig-clear-filter ()
  (interactive)
  (setq agent-rig--filter "")
  (agent-rig-refresh))

(defun agent-rig-command-palette ()
  (interactive)
  (let* ((completion-styles '(substring flex basic))
         (choices (mapcar (lambda (entry)
                            (cons (format "%-9s %s  [%s]" (nth 3 entry) (nth 2 entry) (car entry))
                                  (cadr entry)))
                          (cl-remove-if (lambda (entry) (eq (cadr entry) #'agent-rig-command-palette))
                                        agent-rig--commands)))
         (choice (completing-read "Rig command: " choices nil t)))
    (agent-rig--invoke (cdr (assoc choice choices)))))

(defun agent-rig--cancel-refresh ()
  (when (timerp agent-rig--refresh-timer) (cancel-timer agent-rig--refresh-timer))
  (setq agent-rig--refresh-timer nil))

(defun agent-rig--refresh-visible (buffer)
  (when (and (buffer-live-p buffer) (get-buffer-window buffer t))
    (with-current-buffer buffer
      (condition-case err (agent-rig-refresh)
        (error (setq mode-line-process (format " [%s]" (error-message-string err))))))))

(defconst agent-rig--commands
  '(("RET" agent-rig-open "terminal" "Open")
    ("M-<left>" agent-rig-overview "all agents" "Navigate")
    ("M-<right>" agent-rig-open "selected agent" "Navigate")
    ("d" agent-rig-activity "activity" "Open")
    ("TAB" agent-rig-switch "switch" "Open")
    ("o" agent-rig-capture "output" "Open")
    ("n" agent-rig-start "agent" "Create")
    ("t" agent-rig-start-team "team" "Create")
    ("w" agent-rig-worktree-start "worktree" "Create")
    ("A" agent-rig-adopt "adopt" "Create")
    ("s" agent-rig-send "prompt" "Send")
    ("b" agent-rig-broadcast "broadcast" "Send")
    ("h" agent-rig-handoff "handoff" "Send")
    ("r" agent-rig-restart "restart" "Manage")
    ("x" agent-rig-stop "stop" "Manage")
    ("S" agent-rig-save "save" "Recovery")
    ("R" agent-rig-restore "restore" "Recovery")
    ("i" agent-rig-set-conversation "conversation ID" "Recovery")
    ("a" agent-rig-toggle-projects "all/project" "View")
    ("/" agent-rig-filter "filter agents" "View")
    (":" agent-rig-command-palette "find command" "View")
    ("g" agent-rig-refresh "refresh" "View")
    ("f" agent-rig-toggle-focus "focus" "View")
    ("C-c C-o" agent-rig-return-to-code "return to code" "Navigate")
    ("?" agent-rig-help "all actions" "Navigate")
    ("q" quit-window "close panel" "Navigate")))

(defvar agent-rig-actions-mode-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map special-mode-map)
    (dolist (entry agent-rig--commands)
      (let ((command (cadr entry)))
        (define-key map (kbd (car entry))
                    (lambda () (interactive) (agent-rig--invoke command)))))
    (define-key map (kbd "q") #'quit-window)
    (define-key map (kbd "?") #'quit-window)
    (define-key map (kbd "<escape>") #'quit-window)
    map))

(define-derived-mode agent-rig-actions-mode special-mode "Rig Actions"
  (setq-local display-line-numbers nil)
  (setq-local truncate-lines nil))

(defun agent-rig-help ()
  (interactive)
  (let ((origin (current-buffer))
        (directory (agent-rig--directory))
        (target (when (or agent-rig--terminal-session
                          (and (derived-mode-p 'agent-rig-mode)
                               (or (tabulated-list-get-id) agent-rig--selected-session)))
                  (agent-rig--select))))
    (when (derived-mode-p 'agent-rig-mode) (agent-rig--selection-changed))
    (with-current-buffer (get-buffer-create "*Agent Rig Actions*")
      (agent-rig-actions-mode)
      (setq-local display-line-numbers nil)
      (setq-local agent-rig--action-origin origin)
      (setq-local agent-rig--project-directory directory)
      (let ((inhibit-read-only t))
        (erase-buffer)
        (insert (propertize "AGENT RIG  /  ACTIONS\n" 'face 'agent-rig-title)
                (propertize "q / Esc returns  ·  : finds a command\n\n" 'face 'shadow))
        (when target
          (insert (propertize (format "Target: %s/%s [%s]\n\n" (alist-get 'team target)
                                       (alist-get 'seat target) (alist-get 'provider target)) 'face 'bold)))
        (agent-rig--insert-actions '("Open" "Create" "Send" "Recovery" "Manage" "View"))
        (insert (propertize "[q / Esc] back     [C-c C-o] code\n" 'face 'agent-rig-key))
        (insert (propertize (format "tmux %s  ·  %s  ·  %d/%d CLIs found\n"
                                    (if (executable-find agent-rig-tmux-program) "available" "MISSING")
                                    (if (locate-library "vterm") "vterm" "term")
                                    (cl-count-if (lambda (provider)
                                                   (ignore-errors (agent-rig-provider-command (car provider))))
                                                 agent-rig-providers)
                                    (length agent-rig-providers)) 'face 'shadow)))
      (goto-char (point-min))
      (set-buffer-modified-p nil)
      (agent-rig--display (current-buffer))
      (when (eq (window-parameter (selected-window) 'window-side) 'bottom)
        (fit-window-to-buffer nil (floor (* 0.8 (frame-height))) 10)))))

(defvar agent-rig-mode-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map tabulated-list-mode-map)
    (dolist (command agent-rig--commands)
      (define-key map (kbd (car command)) (cadr command)))
    (dolist (key '("j" "<down>" "C-n"))
      (define-key map (kbd key) #'agent-rig-next-row))
    (dolist (key '("k" "p" "<up>" "C-p"))
      (define-key map (kbd key) #'agent-rig-previous-row))
    (define-key map (kbd "<escape>") #'agent-rig-clear-filter)
    map))

(define-derived-mode agent-rig-mode tabulated-list-mode "Agent Rig"
  (setq tabulated-list-format [("Team" 14 t) ("Seat" 18 t) ("Provider" 12 t)
                               ("Process" 10 t) ("Project" 0 t)])
  (setq tabulated-list-padding 2)
  (setq tabulated-list-sort-key '("Team" . nil))
  (setq-local truncate-lines t)
  (setq-local mode-line-buffer-identification '("Rig  RET open · n new · ? actions"))
  (setq-local hl-line-face 'agent-rig-selection)
  (hl-line-mode 1)
  (add-hook 'post-command-hook #'agent-rig--selection-changed nil t)
  (add-hook 'tabulated-list-revert-hook #'agent-rig-refresh nil t)
  (add-hook 'kill-buffer-hook #'agent-rig--cancel-refresh nil t)
  (add-hook 'change-major-mode-hook #'agent-rig--cancel-refresh nil t)
  (when (and (numberp agent-rig-refresh-interval) (> agent-rig-refresh-interval 0))
    (setq agent-rig--refresh-timer
          (run-with-idle-timer agent-rig-refresh-interval t #'agent-rig--refresh-visible (current-buffer))))
  (tabulated-list-init-header))

(defun agent-rig (&optional all-projects)
  (interactive "P")
  (agent-rig--remember-source)
  (let ((directory (file-name-as-directory (file-truename (agent-rig--directory)))))
    (with-current-buffer (get-buffer-create "*Agent Rig*")
      (unless (derived-mode-p 'agent-rig-mode) (agent-rig-mode))
      (setq agent-rig--project-directory directory default-directory directory
            agent-rig--show-all (not (null all-projects)))
      (agent-rig-refresh)
      (agent-rig--display (current-buffer)))))

(provide 'agent-rig)
