(require 'cl-lib)
(require 'project)
(require 'tabulated-list)
(require 'term)
(require 'agent-rig-providers)
(require 'agent-rig-tmux)

(defvar agent-rig-teams
  '(("pair" ("implementer" codex) ("reviewer" claude-code))
    ("mixed" ("implementer" codex) ("reviewer" claude-code) ("explorer" opencode))))
(defvar agent-rig-terminal-function #'agent-rig-term)
(defvar-local agent-rig--terminal-session nil)
(defvar-local agent-rig--prompt-targets nil)

(defun agent-rig--directory ()
  (let ((project (project-current nil)))
    (if project (car (project-roots project)) default-directory)))

(defun agent-rig--name (name)
  (unless (and (stringp name) (string-match-p "\\`[A-Za-z0-9][A-Za-z0-9_-]*\\'" name))
    (user-error "Names must contain only letters, digits, underscores and hyphens"))
  name)

(defun agent-rig--metadata (team seat provider directory)
  (agent-rig--name team)
  (agent-rig--name seat)
  (when (file-remote-p directory)
    (user-error "Agent Rig supports local project directories"))
  (unless (file-directory-p directory)
    (user-error "Project directory does not exist: %s" directory))
  `((version . 1) (team . ,team) (seat . ,seat)
    (provider . ,(symbol-name provider))
    (directory . ,(file-name-as-directory (file-truename directory)))))

(defun agent-rig--label (session)
  (format "%s/%s [%s] %s" (alist-get 'team session) (alist-get 'seat session)
          (alist-get 'provider session) (alist-get 'directory session)))

(defun agent-rig--select ()
  (let* ((sessions (agent-rig-tmux-sessions))
         (id (or agent-rig--terminal-session
                 (and (derived-mode-p 'agent-rig-mode) (tabulated-list-get-id))))
         (selected (cl-find id sessions :key (lambda (item) (alist-get 'session item)) :test #'equal)))
    (or selected
        (let ((choices (mapcar (lambda (item) (cons (agent-rig--label item) item)) sessions)))
          (unless choices (user-error "No managed agents; use agent-rig-start"))
          (cdr (assoc (completing-read "Agent: " choices nil t) choices))))))

(defun agent-rig-start (team seat provider directory)
  (interactive
   (list (read-string "Team: " "default")
         (read-string "Seat: ")
         (intern (completing-read "Provider: " agent-rig-providers nil t))
         (read-directory-name "Project: " (agent-rig--directory) nil t)))
  (let* ((metadata (agent-rig--metadata team seat provider directory))
         (command (agent-rig-provider-command provider))
         (session (agent-rig-tmux-start metadata command)))
    (when (called-interactively-p 'interactive)
      (agent-rig)
      (agent-rig-open (cl-find session (agent-rig-tmux-sessions)
                               :key (lambda (item) (alist-get 'session item)) :test #'equal)))
    session))

(defun agent-rig-start-team (team directory)
  (interactive
   (list (completing-read "Team template: " agent-rig-teams nil t)
         (read-directory-name "Project: " (agent-rig--directory) nil t)))
  (let ((spec (cdr (assoc team agent-rig-teams))) plans seats existing started)
    (unless spec (user-error "Unknown or empty team: %s" team))
    (dolist (member spec)
      (unless (and (listp member) (= (length member) 2) (symbolp (cadr member)))
        (user-error "Invalid team member: %S" member))
      (when (member (car member) seats) (user-error "Duplicate seat: %s" (car member)))
      (push (car member) seats)
      (push (list (agent-rig--metadata team (car member) (cadr member) directory)
                  (agent-rig-provider-command (cadr member))) plans))
    (setq existing (agent-rig-tmux-sessions))
    (dolist (plan plans)
      (when (cl-find-if
             (lambda (session)
               (cl-every (lambda (key) (equal (alist-get key session) (alist-get key (car plan))))
                         '(team seat directory))) existing)
        (user-error "Seat already exists: %s" (alist-get 'seat (car plan)))))
    (condition-case err
        (dolist (plan (nreverse plans))
          (push (agent-rig-tmux-start (car plan) (cadr plan)) started))
      (error
       (dolist (session started)
         (ignore-errors (agent-rig-tmux--run "kill-session" "-t" (concat "=" session))))
       (signal (car err) (cdr err))))
    (when (called-interactively-p 'interactive) (agent-rig))
    (nreverse started)))

(defun agent-rig-term (session)
  (let* ((id (alist-get 'session session))
         (name (concat "agent-rig:" (substring id 3 15)))
         (buffer (get-buffer (concat "*" name "*")))
         (default-directory (alist-get 'directory session))
         (process-environment (copy-sequence process-environment)))
    (setenv "TMUX" nil)
    (unless (and buffer (process-live-p (get-buffer-process buffer)))
      (when buffer (kill-buffer buffer))
      (setq buffer (make-term name agent-rig-tmux-program nil
                              "-L" agent-rig-tmux-socket "attach-session" "-t" (concat "=" id)))
      (with-current-buffer buffer
        (term-mode)
        (term-char-mode)
        (setq-local agent-rig--terminal-session id)))
    (pop-to-buffer buffer)))

(defun agent-rig-open (&optional session)
  (interactive)
  (funcall agent-rig-terminal-function (or session (agent-rig--select))))

(defun agent-rig-capture ()
  (interactive)
  (let* ((session (agent-rig--select))
         (text (agent-rig-tmux--run "capture-pane" "-p" "-J" "-S" "-2000"
                                   "-t" (alist-get 'pane session))))
    (with-current-buffer (get-buffer-create "*Agent Rig Output*")
      (let ((inhibit-read-only t))
        (erase-buffer)
        (insert (agent-rig--label session) "\n\n" text))
      (special-mode)
      (pop-to-buffer (current-buffer)))))

(defun agent-rig-stop ()
  (interactive)
  (let ((session (agent-rig--select)))
    (when (yes-or-no-p (format "Stop %s and discard its terminal history? " (agent-rig--label session)))
      (agent-rig-tmux--run "kill-session" "-t" (concat "=" (alist-get 'session session)))
      (when (derived-mode-p 'agent-rig-mode) (agent-rig-refresh)))))

(defun agent-rig-restart ()
  (interactive)
  (let ((session (agent-rig--select)))
    (unless (equal (alist-get 'status session) "exited")
      (user-error "Only exited agents can be restarted"))
    (when (yes-or-no-p "Start a fresh provider conversation in this seat? ")
      (agent-rig-tmux--run "respawn-pane" "-t" (alist-get 'pane session))
      (agent-rig-open session))))

(defun agent-rig--compose (targets &optional text)
  (let ((buffer (generate-new-buffer "*Agent Rig Prompt*")))
    (with-current-buffer buffer
      (text-mode)
      (setq-local agent-rig--prompt-targets (mapcar (lambda (item) (alist-get 'session item)) targets))
      (setq-local header-line-format
                  (format "To: %s | C-c C-c: paste draft, then submit in agent terminal"
                          (mapconcat #'agent-rig--label targets ", ")))
      (use-local-map (copy-keymap text-mode-map))
      (local-set-key (kbd "C-c C-c") #'agent-rig-paste-prompt)
      (when text (insert text)))
    (pop-to-buffer buffer)))

(defun agent-rig-send ()
  (interactive)
  (agent-rig--compose (list (agent-rig--select))))

(defun agent-rig-send-region (begin end)
  (interactive "r")
  (let ((text (buffer-substring-no-properties begin end)))
    (agent-rig--compose (list (agent-rig--select)) text)))

(defun agent-rig-broadcast ()
  (interactive)
  (let* ((selected (agent-rig--select))
         (targets (cl-remove-if-not
                   (lambda (item)
                     (and (equal (alist-get 'team item) (alist-get 'team selected))
                          (equal (alist-get 'directory item) (alist-get 'directory selected))
                          (equal (alist-get 'status item) "running")))
                   (agent-rig-tmux-sessions))))
    (unless targets (user-error "No running agents in this team"))
    (agent-rig--compose targets)))

(defun agent-rig-paste-prompt ()
  (interactive)
  (unless agent-rig--prompt-targets (user-error "No pending prompt targets"))
  (let ((text (buffer-substring-no-properties (point-min) (point-max)))
        (sessions (agent-rig-tmux-sessions)) delivered)
    (dolist (target (copy-sequence agent-rig--prompt-targets))
      (let ((session (cl-find target sessions :key (lambda (item) (alist-get 'session item)) :test #'equal)))
        (unless session (user-error "Agent disappeared: %s" target))
        (agent-rig-tmux-paste session text)
        (setq agent-rig--prompt-targets (delete target agent-rig--prompt-targets))
        (push session delivered)))
    (setq header-line-format "Draft pasted. Submit it in each agent terminal.")
    (set-buffer-modified-p nil)
    (message "Pasted to %d agent(s); submit in their terminals" (length delivered))
    (when (= (length delivered) 1) (agent-rig-open (car delivered)))))

(defun agent-rig-refresh ()
  (interactive)
  (setq tabulated-list-entries
        (mapcar (lambda (session)
                  (list (alist-get 'session session)
                        (vector (alist-get 'team session) (alist-get 'seat session)
                                (alist-get 'provider session)
                                (if (equal (alist-get 'status session) "exited")
                                    (concat "exited:" (alist-get 'exit-code session)) "running")
                                (alist-get 'directory session))))
                (agent-rig-tmux-sessions)))
  (tabulated-list-print t))

(defvar agent-rig-mode-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map tabulated-list-mode-map)
    (define-key map (kbd "g") #'agent-rig-refresh)
    (define-key map (kbd "n") #'agent-rig-start)
    (define-key map (kbd "t") #'agent-rig-start-team)
    (define-key map (kbd "RET") #'agent-rig-open)
    (define-key map (kbd "s") #'agent-rig-send)
    (define-key map (kbd "b") #'agent-rig-broadcast)
    (define-key map (kbd "o") #'agent-rig-capture)
    (define-key map (kbd "r") #'agent-rig-restart)
    (define-key map (kbd "k") #'agent-rig-stop)
    map))

(define-derived-mode agent-rig-mode tabulated-list-mode "Agent Rig"
  (setq tabulated-list-format [("Team" 16 t) ("Seat" 20 t) ("Provider" 14 t)
                               ("Process" 12 t) ("Project" 0 t)])
  (setq tabulated-list-padding 2)
  (setq tabulated-list-sort-key '("Team" . nil))
  (setq-local header-line-format "n: new  t: team  RET: terminal  s: prompt  b: broadcast  o: output  r: restart  k: stop  g: refresh")
  (add-hook 'tabulated-list-revert-hook #'agent-rig-refresh nil t)
  (tabulated-list-init-header))

(defun agent-rig ()
  (interactive)
  (with-current-buffer (get-buffer-create "*Agent Rig*")
    (agent-rig-mode)
    (agent-rig-refresh)
    (pop-to-buffer (current-buffer))))

(provide 'agent-rig)
